### ISSUE TITLE
Assets for website

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#10]
### Overview
We will collect assets to put onto website in this issue

### Action Items
- [x] First Item
   - [x] Workshop for Automation https://www.meetup.com/hackforla/events/qlggsrybckbdc/

### Resources/Instructions
[100Automations Youtube Channel](https://www.youtube.com/channel/UCS_BOwZ5Hj3pGHN0gmx4gAA/?guided_help_flow=5)

**Comment by myastark** [comment]
[bn-icons.zip](https://github.com/hackforla/ballotnav/files/5212066/bn-icons.zip)
