### ISSUE TITLE
Name of responsible official for users EAJ (Design)

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#107]
### Overview
Users will be able to see the first name and last name of their Election Administration Jurisdiction official. This allows users to have relevant information delivered to them. 

### Acceptance criteria
(how do we know when this task is "Done")
- [ ] search for an address
- [ ] choose a result off the result display 
   - [ ] location details show header 'Your Responsible Official' with the First Name and Last Name of the users EAJ official
- [ ] results match mockups
   - [ ] desktop 
   - [ ] desktop low bandwidth
   - [ ] mobile
   - [ ] mobile low bandwidth
- [ ] Users can see their responsible EAJ official at following locations
   - [ ] Location detail 

### Dependency 
Search by address feature #42 

### Action Items
- [ ] UX 
   - [ ] text for what shows up 
- [ ] UI 
  - [ ] Location details page shows the First Name, Las Name of users respective EAJ 

### Resources/Instructions
[Figma](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=344%3A3232)
EAJ = Election Administration Jurisdiction

**Comment by myastark** [comment]
<img width="157" alt="87" src="https://user-images.githubusercontent.com/54009156/93800820-fd182a00-fbf5-11ea-92f1-f0688da51374.png">

**Comment by kcoronel** [comment]
@IrinaRost @fedelandini please review this issue

**Comment by IrinaRost** [comment]
@kcoronel in the location details we have "to verify" block near the button "directions". Is it what this issue means?
