### ISSUE TITLE
Location Header (Design)

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#117]
### Overview
We need an area to display the state and EAJ location info. In order to confirm with the user that we are displaying the correct info, and if not, allow them to correct it. 

### Dependency 
feature search by address #42 
invalid address feature #112 

### User Acceptance Criteria 
- [x] Use search by address field to get delivered to a list of ballot drop off sites in user EAJ
   - [x] Enter valid address 
      - [x] see your state at the top of the drop down
      - [x] see your EAJ at the top of your drop down
      - [x] see your EAJ at the top of your drop down,  change it to another EAJ, wipes out previous map 
           - [x] results below (map and location summaries) should change to match what you chose
      - [x] see your state at the top of the drop down, change it to another state, wipes out previous map 
          - [x] changes the county to the words "Choose your" + ${EAJ} (where EAJ is replaced with the type of EAJ example: city, county, parish, district, etc.)
    - [x] Enter an invalid address 
       - [x] see a dropdown of states and county drop down is hidden.  
       - [x] see search bar again so that you can put in your address again
       - [x] see language where map and locations result normally would be, that instead explains that we could not find your address, and some suggestions for how to format address, or to use the drop downs above.
- [x] Additional test once you have a valid address 
    - [x] click see more info (actual language TBD based on UX writing) 
        - [x] All links should behave according to issue #90 
- [x] Additional test when you have an invalid address 
    - [x] verify you cannot see more info 
- [x] Words that give you drop down (example: Expand to Learn) 
    - [x] Insider of header
    - [x] Links to vote.org and sos (example: We have found the most credible and up to date state and EAJ changes to be on vote.org. Click here to read the current updates for (user state) from vote.org and the SOS. )
    - [x] Notifications Sign- Up (example: get notified of SOS election page changes and vote.org covid19 page changes for your state )
      - [x] error message (search instructions) 

### Action Items
- [x] UX
   - [x] Write language  
     - [x] header 
        - [x] Words that give you drop down (example: Expand to Learn) 
        - [x] Insider of header
            - [x] Links to vote.org and sos (example: We have found the most credible and up to date state and EAJ changes to be on vote.org. Click here to read the current updates for (user state) from vote.org and the SOS. )
            - [x] Notifications Sign- Up (example: get notified of SOS election page changes and vote.org covid19 page changes for your state )
      - [x] error message (search instructions) 
- [x] UI 
   - [x] Use search by address field to get delivered to a list of ballot drop off sites in user EAJ
      - [x] Enter valid address 
         - [x] see your state at the top of the drop down
         - [x] see your EAJ at the top of your drop down
         - [x] see your EAJ at the top of your drop down, change it to another EAJ, results below (map and location summaries) 
 should change to match what you chose
         - [x] see your state at the top of the drop down, change it to another state, and it changes the county to the words "Choose your" + ${EAJ} (where EAJ is replaced with the type of EAJ example: city, county, parish, district, etc.) and there will be a message to do same where map used to be.
       - [x] Enter an invalid address 
          - [x] see a dropdown of states and county drop down is hidden.  
          - [x] see search bar again so that you can put in your address again
          - [x] see language where map and locations result normally would be, that instead explains that we could not find your address, and some suggestions for how to format address, or to use the drop downs above.
   - [x] Additional test once you have a valid address 
       - [x] click see more info (actual language TBD based on UX writing) 
          - [x] All links should behave according to issue #90 
   - [x] Additional test when you have an invalid address 
       - [x] verify you cannot see more info 

### Resources/Instructions
EAJ = Election Administration Jurisdiction 
SOS = Secretary of State

**Comment by aNullValue** [comment]
"State will remain populated" may not be feasible. The front-end needs to be able to start from "nothing" (not even state) in event geocoding fails.

**Comment by myastark** [comment]
<img width="719" alt="177" src="https://user-images.githubusercontent.com/54009156/93800582-a9a5dc00-fbf5-11ea-8c93-cfc538ae5eaf.png">

**Comment by myastark** [comment]
Wait, how is " Notifications Sign- Up (example: get notified of SOS election page changes and vote.org covid19 page changes for your state )" different from #78 ?

**Comment by myastark** [comment]
### “Expand” Call-to-Action
Voting Safety Information
_[^Button]_

### Expanded

- [ ]  Have you checked your registration? **[vote.org tool modal]**
- [ ]  Do you need to register? **[vote.org tool modal]**
- [ ] Do you need to request a mail-in/absentee ballot? **[vote.org tool modal]**
- [ ] Before you go, have you checked for last-minute changes to voting rules and COVID-19 safety information for your State? **[link=vote.org COVID page State anchor, target=_blank]**
- [ ] Before you go, have you checked for last-minute changes at your chosen location? **[Can this jump them down to their search results?]**
_[Checkboxes ^ are suggested non-clickable graphic element]
[The end of this is where I get confused with #78 - would the notification signup go here?]_

### Error
Warning: Voting rules vary by [EAJ]. Please confirm or choose again

**Comment by kcoronel** [comment]
@fedelandini @IrinaRost do you mind double confirming that we have a mock up of the above description. Thanks!

**Comment by IrinaRost** [comment]
@kcoronel we checked this issue, it looks like we have all mockups, so you can close the issue
