### ISSUE TITLE
Gather & Validate Information Display Requirements

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#12]
### Overview
We need to review the information we intend to collect so that we can present ballot information in a way that is valuable to our audience

### Dependency 
Competitor/Resource research #14 

### Action Item
- [x]  List out all data types we would need to make resource useful 
- [x] Review the template with team and validate with outside stakeholders
- [x] Test the model with scrapers

### Resources
[BallotNav Data Collection Starting Point](https://docs.google.com/spreadsheets/d/1Nir81gZNcQgdTTC3vMNuiUkRe0g-CLOIgN53Csp41rw/edit#gid=814856157)

**Comment by myastark** [comment]
I don't know if this is the right place to put this, but I feel like each state/county, however it breaks down, should have a person who accepts responsibility for getting notifications when source pages update, and inputting those changes. Here's [some services](https://www.hongkiat.com/blog/detect-website-change-notification/) that do that.

**Comment by kcoronel** [comment]
I sent a request to Airtable

**Comment by ExperimentsInHonesty** [comment]
Let setup on the free tier.

**Comment by kcoronel** [comment]
@myastark I moved your comment
