### ISSUE TITLE
EAJ Details Expansion 

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#122]
### Overview

We need to let users view the details for their respective Election Administration Jurisdiction by expanding the EAJ dropoff location summary view. 

### Dependency
Search by address #42 
Location header #117 
Share location #86 
Name of responsible EAJ official #107 
External link handling #90 
Guidance to double-check information #111 

### User Acceptance Criteria
(how do we know when this task is "Done")
- [ ] User uses input bar to get delivered to a list of ballot drop off sites in your EAJ 
- [ ] List of EAJ locations is provided to the user in list form and as pins on the map
- [ ] User can click on each individual result to bring down additional details about location - see "Checklist Steps" and "Individual Result Display Requirement." 
- [ ] results match mockups
   - [ ] desktop 
   - [ ] desktop low bandwidth
   - [ ] mobile
   - [ ] mobile low bandwidth

### Checklist steps
1. Check to make sure you are registered to vote 
2. Register to vote
3. Register for an absentee ballot
4. Confirm ballot dropoff location information below is still accurate by contacting your location directly before you go

### Individual result display requirement 
- [ ] Name 
- [ ] Type of location 
- [ ] Inside or Outside            
- [ ] Address 
- [ ] Accessibility Icon 
- [ ] Distance 
- [ ] Travel Times (Provide all that mapbox will return) example - bus, train, car, walking, etc
- [ ] Hours 
   - [ ] No hours (if we don't have hours for this location prompt them to sign up for notifications)  
   - [ ] Open Now: Open until 9pm PDT (more hours - is a link to hour display on the detail card) #108 
- [ ] Share this location 
- [ ] URL to vote.org 
- [ ] URL to SOS website 
- [ ] Sign up to get notifications for changes to SOS website and/or this location 
- [ ] Directions Button
- [ ] Website Link
- [ ] Phone Number
- [ ] To Verify

### Action Items
- [ ] Product
   - [ ] Determine text to be displayed 
   - [ ] Confirm text layout 
   - [ ] Identify error handling requirements (can't think of any errors) 
- [ ] UI/UX
   - [ ] List should display text/information in correct locations 
   - [ ] Make mockup
- [ ] Font End Dev (React)
   - [ ] Build out display according to design spec
- [ ] Back End
   - [ ] TBD

### Resources/Instructions
[Figma](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=344%3A3232)
[am I registered to vote tool](https://www.vote.org/am-i-registered-to-vote/)

**Comment by myastark** [comment]
### Expanded

- [ ]  Have you checked your registration? **[vote.org tool modal]**
- [ ]  Do you need to register? **[vote.org tool modal]**
- [ ] Do you need to request a mail-in/absentee ballot? **[vote.org tool modal]**
- [ ] Before you go, have you checked for last-minute changes to voting rules and COVID-19 safety information for your State? **[link=vote.org COVID page State anchor, target=_blank]**
- [ ] Before you go, have you checked for last-minute changes at your chosen location? **[Can this jump them down to their search results?]**
_[Checkboxes ^ are suggested non-clickable graphic element]
[The end of this is where I get confused with #78 - would the notification signup go here?]_

### Error
Warning: Voting rules vary by [EAJ]. Please confirm or choose again
