### ISSUE TITLE
Competitor Research/Resources 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#14]
### Overview
Find out how other websites approach delivering similar information to see what we can implement with our own 

### Action Items

- [x] Search the web for 3-4 competitors/resources 
- [x] Fill out competitive analysis template

### Resources/Instructions
[Ballot Nav Competitive analysis](https://docs.google.com/spreadsheets/d/120nn4eM1G3Kbdsfhpzko-9o5xzsm9X19OJJVf-ooRg0/edit#gid=0)

[Example of competitor](https://projects.fivethirtyeight.com/how-to-vote-2020/)

**Comment by kcoronel** [comment]
@myastark @Arjayellis When you get a chance, please add to this resource document. Thanks

**Comment by kcoronel** [comment]
Update 08/30, I have filled out the competitor analysis for my three assigned organizations

**Comment by Arjayellis** [comment]
Completed for my competitors

**Comment by ExperimentsInHonesty** [comment]
team did a ton.  Good job
