### ISSUE TITLE
Write Project Requirements Summary Document 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#15]
### Overview
We need a requirements summary to share with website design and to complete the initial requirements gathering milestone.

### Dependency
Requirements gathering milestone complete

### Action Items
- [ ]  Review all the items in the [requirements gathering milestone](https://github.com/hackforla/ballotnav/projects/1)
- [ ] Write summary
- [ ] Close issue and check to make sure milestone shows as completed

### Resources/Instructions
- [BallotNav Website Requirements Gathering Summary](https://docs.google.com/document/d/1YUqyA9D6tsLTO5PSlL_ZIBGBTp5DKF5U88iSOaBviPk/edit)
- [BallotNav Figma Board with Content Outline](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=18%3A40)
- [100Automations Website Requirements Gathering Summary](https://docs.google.com/document/d/1EoY96gsM32lZf4QgmrQVGVZVB67Ay3uGHrd7Jq5bDOc/edit)

**Comment by Arjayellis** [comment]
Give users two choices: 1) Search by address/zip, 2) search by state then county.
