### ISSUE TITLE
Decide/develop our own style guide

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#18]
### Overview
Develop style guide for the overall navigation and visual appearance of the site.

### Action Items
- [ ] Define a color guide
- [ ] Define a typography system
- [ ] Create key components

### Resources/Instructions
Figma File 
[Stylesheet for BallotNav Logo](https://github.com/hackforla/ballotnav/files/5211046/ballotnav.branding.pdf)

**Comment by kcoronel** [comment]
Stylesheet [Uploading ballotnav branding.pdf…]

**Comment by JacobZwang** [comment]
For now, I'm using 

:root {
  --ballotBlue: #1b2152;
  --ballotBlueDark: #040822;
  --routeRed: #ff0029;
  --routeRedDark: #6e0012;
}

until there is a final consensus

**Comment by kcoronel** [comment]
@IrinaRost and @fedelandini can you please post the site style guide to this issue at your earliest convenience. Thank you!

**Comment by IrinaRost** [comment]
In progress

**Comment by staceyrebekahscott** [comment]
Closing this issue, see issue #435 for more details.
