### ISSUE TITLE
Meeting Time Change

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#186]
### Overview
We need to change the Tuesday meeting time

### Action Items
- [ ] Change current time for BallotNav Tuesday meeting from "6:00PM - 7:30PM" to "5:00PM - 6:30PM"

**Comment by Arjayellis** [comment]
@Rankazze @KianBadie

**Comment by Rankazze** [comment]
@Arjayellis https://github.com/hackforla/VRMS/issues/338   Please follow up with @alex-anakin in 24 hrs about status to completion.

**Comment by KianBadie** [comment]
@Arjayellis just wanted to give a heads up that meetings times are retrieved from the VRMS service and then displayed on the HFLA website. So once the meetings times are changed there (which it looks like [this](https://github.com/hackforla/VRMS/issues/338) issue is for), it will display on our site.

**Comment by Rankazze** [comment]
@Arjayellis The new time is displaying on HfLA website.  Please close after you confirm tomorrow.  Cheers,  Thanks @alex-anakin

**Comment by kcoronel** [comment]
I am working with Adam Spar on this 
<img width="591" alt="Screen Shot 2020-11-12 at 6 11 33 PM" src="https://user-images.githubusercontent.com/38144130/99020100-b3bbcb00-2512-11eb-8e39-59f9be8ddc25.png">
