### ISSUE TITLE
Role Recruitment

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#19]
### Overview
We need to recruit contributors for this project on an ongoing basis in order to make sure that the site goes live in a timely manner. 

### Action Items
- [x] Check BallotNav items on recruiting sheet and update as necessary

### Resources/Instructions
- [Hack for LA Recruiting Current Needs](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0
)

**Comment by Arjayellis** [comment]
Business Analyst (Category: BA)
Technical Architect (Category: Developer)
UI Designer (Category: UI/UX)
UX Researcher (Category: UI/UX)

**Comment by Arjayellis** [comment]
@kcoronel @ExperimentsInHonesty Dane mentioned he did not get must interest from hack night. Most of the individuals were there to see the speakers. He will continue to advertise through slack. I am going to reach out to a few channels and to my network to see if we can spark some interest.

**Comment by Arjayellis** [comment]
@kcoronel @ExperimentsInHonesty Reached out to Ben and Jared about beginning to see what we can replicate from FO. The goal will be to hopefully get something set up within the next week so we can have something set up for the volunteers.
