### ISSUE TITLE
Have VRMS add meeting times for BallotNav to project and event database

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/ballotnav#2]
### Overview
Get VRMS to add this project to its database so that meeting times can appear on the website team meeting page

### Action Items
- [x] List out team meeting info
    - [x] Tuesdays: 6:00-8:00 (Pacific) Team Meeting
    - [x] Saturdays: 4:00pm-6:00pm (Pacific) Management Meeting
- [x] Reach out to Tech Lead or PM on the vrms slack channel with a link to this issue
- [ ] After they indicate completion, check the website.

### Resources/Instructions
https://www.hackforla.org/project-meetings
slack channel for VRMS team is vrms.

**Comment by kcoronel** [comment]
@Arjayellis I am available Tuesday - Thursday from 5:30pm - 7:30pm

**Comment by Arjayellis** [comment]
@myastark @kcoronel @ExperimentsInHonesty I am available Tuesday and Thursday from 6 - 8PM, and Saturday from 4 - 5PM

**Comment by myastark** [comment]
I am available Mondays, Fridays, Saturdays, and Sundays, and Tues-Thurs from 5pm on

**Comment by ExperimentsInHonesty** [comment]
@Arjayellis @kcoronel Lets meet at 4pm on saturdays for a working meeting.  Then @myastark can join us at 5pm once we get all organized.  The meeting will be a total of 2 hours working meeting.  
I suggest you pick another time to meet with each other mid week to onboard new team members and divy out issues.  This project needs a higher cadence given the deadline involved.  I suggest 6pm-8 Tuesday.

If that mostly works, let me know so I can help you get this listed on the website via VRMS.

**Comment by kcoronel** [comment]
That works for me @ExperimentsInHonesty @Arjayellis, if we would like to meet tomorrow, I can place it in our Slack channel to get folks on-boarded and potentially give them some tasks?

**Comment by Arjayellis** [comment]
That works for me as well. @kcoronel @ExperimentsInHonesty. Are you available to chat about listing on VRMS, or would you like to tackle that tomorrow?

**Comment by Rankazze** [comment]
Here is the open issue on the VRMS board for this issue
https://github.com/hackforla/VRMS/issues/271

**Comment by ExperimentsInHonesty** [comment]
checked meeting times on site.  Not yet up.

**Comment by kcoronel** [comment]
Randall reached out on 9/1 for an update on our info getting on the site

**Comment by ExperimentsInHonesty** [comment]
This is good.  Showing up on the site perfectly now.
