### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#20]
### Overview
We need an up to date ReadMe to communicate effectively new users, contributors, and visitors on a continuous basis.

### Action Items
- [x] Once that happens, update link in ReadMe to the template
- [x] New person to review ReadMe identifying unanswered questions that could be addressed
  - [x] Post suggestions in the comments below

### Resources/Instructions
- [BallotNav ReadMe](https://github.com/hackforla/ballotnav/blob/master/README.md)

**Comment by ExperimentsInHonesty** [comment]
@Arjayellis and @kcoronel  I just noticed in the readme that you linked to your names, but it dosent work to right click on your name you have to use a specific url

it should look like this: https://hackforla.slack.com/team/UE1UG1YFP
where the number at the end is the member ID
and you get your member id by going to your profile
clicking more, and then clicking on copy
![Screen Shot 2020-08-24 at 6 35 38 PM](https://user-images.githubusercontent.com/37763229/91112774-d25ba580-e638-11ea-8303-468427347217.png)

**Comment by Arjayellis** [comment]
That was me. I’ll fix it

**Comment by Arjayellis** [comment]
Updated readme with new meeting times
