### ISSUE TITLE
Recruitment of last mile updaters

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#22]
### Overview
Recruit volunteers who are willing to make calls to find the most up to date information regarding ballot drop off (most likely at county level for all 50 states)  

### Action Items
- [x] Find areas to recruit 
- [x] Assign PM to attend meeting, etc. to recruit 
- [x] Create a functional spreadsheet for the recording of information 
- [x] Product 
    - [x] Create an adopt a county form 
    - [x] Registration Page (for updating data) [Food Oasis Registration Form](https://ca.foodoasis.net/register)
    - [x] Finalize Language and graphics for 'Claim an EAJ' recruitment 
        - [x] Share language to CFA general Slack page and friendly areas **by cross posting ex: "cross posting here (take link of original post) for BallotNav, we should have the interface ready in a week **
- [x] Markting/Partnerships 
    - [x] Create an on-boarding guide for volunteers Example [Food Oasis volunteer](https://docs.google.com/presentation/d/1C5sBHUw6OTN_Tf6UMq_3DqLqXGvCIXs8VBZIz_Fo3o/edit#slide=id.g52d92714eb_1_14)
    - [ ] Create video on-boarding presentation Example [Food Oasis Video](https://us02web.zoom.us/rec/share/PgZO63p4R4DtFwWHTOsjv08vmo8VMmMsdEe1hhdyuIrGXprJeY6fnoU2ZjZ1TK60.3WwhwDzq-eWhEjtf)

### Resources/Instructions
- [BallotNav Volunteer Training](https://docs.google.com/presentation/d/1Szr2WeDNQ6gngIqL5Z811EqSuUtUM9A7RCLFJhIGSU8/edit?usp=sharing)
- [Volunteer Dashboard](https://admin.dev.ballotnav.org/login)

**Comment by kcoronel** [comment]
Reached out to [When We All Vote ](https://www.whenweallvote.org/partner-with-us/?ref=667dc2d6-96ea-473b-b9ee-22e4fbf35667) Please see attached for email confirmation

**Comment by Arjayellis** [comment]
Followed up with when we all vote about a potential partnership. We also received a commitment from a Stanford group to help make calls closer to election day.

**Comment by kcoronel** [comment]
From @myastark I feel like each state/county, however it breaks down, should have a volunteer who accepts responsibility for getting notifications when source pages update, and inputting those changes. Here's some services that do that.

**Comment by kcoronel** [comment]
added food oasis onboarding material in this issue

**Comment by kcoronel** [comment]
@Arjayellis can you please post the infographic you worked on in here and tag Rachel

**Comment by Arjayellis** [comment]
![my-visual_49117381](https://user-images.githubusercontent.com/69663209/93915618-2780ea80-fcbd-11ea-9af1-a929065ce05e.png)
@makecation

**Comment by makecation** [comment]
@Arjayellis nice! Do you have an editable version of this?

**Comment by Arjayellis** [comment]
[paper_49135621.zip](https://github.com/hackforla/ballotnav/files/5265712/paper_49135621.zip)

@makecation Here is a version in blocks. Will that work? Otherwise, I can give you access to my pikchart account.

**Comment by makecation** [comment]
@Arjayellis thanks! If I can access your pikchart account I imagine that would save some time (since it appears to only let you export static images).

**Comment by Arjayellis** [comment]
@myastark please see the infographic above. Would you like to write us some copy for the fields?

**Comment by kcoronel** [comment]
@makecation please see some copyedits below. I think we want to make this first form more of an interest form, given the time. 
-------------------------------
BallotNav needs your help! 

BallotNav is a project of Hack for LA, the Los Angeles brigade of Code for America. BallotNav will help voters quickly find the location, and  times of operation for dropping off mail-in ballots in person.

The ask: We need folks to make calls to election administration jurisdictions across the country and verify the information we have collected. 

Interested? Fill out the volunteer form at bit.ly/BallotNav. 

We will follow-up with next steps. Any questions, reach us at ballotnav@hackforla.org

**Comment by makecation** [comment]
@kcoronel here's a couple ideas. I've made it in a more shareable square format. 

![Ballotnav-Recruitment-Infographic-A](https://user-images.githubusercontent.com/34785444/95286494-56986f80-0818-11eb-8259-0308c4868391.png)

![Ballotnav-Recruitment-Infographic-B](https://user-images.githubusercontent.com/34785444/95286500-5d26e700-0818-11eb-8ce0-ab6ecc088cfa.png)

**Comment by Arjayellis** [comment]
@kcoronel @makecation @ExperimentsInHonesty These are great! In the second, should the text in the top section after "BallotNav needs your help" be the same color as the text in the green speech bubble below? Might be easier to read at a quick glance. Overall, I think I like the first better. Also, not sure if it's worth mentioning a quick snippet about why it's important that people have the option to drop off in person?

**Comment by makecation** [comment]
Thanks for the feedback @Arjayellis - here are a few more revised options per your suggestions. The wording I added might need some help too. 

![Ballotnav-Recruitment-Infographic-2A](https://user-images.githubusercontent.com/34785444/95376101-6efa9f80-0895-11eb-8546-800bf4fb25f7.png)

![Ballotnav-Recruitment-Infographic-2B](https://user-images.githubusercontent.com/34785444/95376112-70c46300-0895-11eb-8ef2-b5f3403c9499.png)

**Comment by Arjayellis** [comment]
@makecation These look great. @kcoronel do you have a preference between the two?
