### ISSUE TITLE
Recruit from CFA events 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#23]
### Overview
Finding volunteers from CFA events 

### Action Items
- [x] From Bonnie: The Data science team has shown interest for scrapping information from existing sites for populating BallotNav database 
- [x] chat with Bonnie re: CFA Regional Call (once a month) 
- [x] CFA Pitch Day 09/28

**Comment by kcoronel** [comment]
I attended the first CFA West Region meeting on 08/30 and was asked to send an email for folks can get volunteers from their brigade

**Comment by kcoronel** [comment]
@ExperimentsInHonesty @Arjayellis I wrote this draft email for Bonnie to send to the regional western brigade team who all expressed interest in letting their brigades know about BallotNav. Please pay close attention to how I'm asking folks to contact us, there might be a more efficient way. 


Hello! 

HackforLA is recruiting volunteers across the country to to help collect data for BallotNav before the November election. 

BalloNav will help voters quickly find the location, times of operation, and due date for dropping off mail-in ballots in person. Due to COVID19 and cuts to the United States Postal Service, some voters may feel insecure not only about going out to the polls, but even with utilizing the mail to cast their vote. While it is possible to drop off your mail-in ballot in person, the rules for doing so are not clearly outlined in one single location. Information is scattered across state and county offices, each of which individually may fail to provide one or more elements of crucial information such as available ballot drop-off times. 

Volunteers should be willing to donate 3-6hours a week for the purposes of: 
- call county offices and find out the most up to date information for voters 
- update county information accordingly every day for the two weeks leading to the election 

You can learn more about the project at https://github.com/hackforla/ballotnav. If you are interested in joining the team, please send an email to  BallotNav@hackforla.org with your name, brigade, and best form of contact. 

Thanks for your willingness to help out–let’s make voting easier for everyone!

**Comment by kcoronel** [comment]
@ExperimentsInHonesty can you please connect me with Will re: adding BallotNav to the CFA slack for better alignment on volunteers - thanks!

**Comment by Arjayellis** [comment]
The message looks good to me. Explains what we need, why we need it, and how to help. What is the next step?

**Comment by kcoronel** [comment]
Great! Let me send that out to folks on the call and I will copy you.

**Comment by Arjayellis** [comment]
Signed up for CFA pitch day - 9/28

**Comment by ExperimentsInHonesty** [comment]
@karen I just talked to @Arjayellis and he is going to update the readme on the repo with the types of users you are looking for, what we need from them, and how specifically they can get involved.  That way we keep one source of truth for the most current information as it evolves.  He is also going to create an issue for making a google form for interest so that we can start signing up brigades now to update the info later.

Also, I asked Mya to point the DNS at the readme so soon we will be able to just send everyone there.

**Comment by kcoronel** [comment]
great @Arjayellis let me know if you need any support
