### ISSUE TITLE
Dashboard Edits 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#240]
### Overview 
Updating the volunteer dashboard, hiding any extra data points we don't want collected right now and having a password recovery for the volunteer portal. 

### User Acceptance Criteria 
- [ ] Forgot Password appears in sign-up page under "Need an account? Register here." 

### Action Items
- [ ] A Magic link is sent to user for password recovery 
- [ ] Hide the following from "Add New Location Dropdown" 
    - [ ] Hide is Early Dropoff Location 
    - [ ] Hide is Early Voting Location 
    - [ ] Hide is Polling Location 
    - [ ] Hide is Staffed Location 
    - [ ] Hide is Drive Up 

###Resources/Instructions 
[BallotNav](https://admin.dev.ballotnav.org/login)

**Comment by jmensch1** [comment]
hey @jafow, do you have any thoughts about using AWS' SES service for the magic link/password reset portion of this? Food oasis uses Sendgrid for their email stuff, but that would require a new account, additional infrastructure, etc.
