### ISSUE TITLE
Georgia Election Process Validation

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#249]
### Overview
We need to verify the ballot drop off process in Georgia to determine technical requirements 

### Action Items
- [x] Call top 25 counties in Georgia (100K+ population) and add notes to each row about policy

### Resources/Instructions
[Georgia data](https://docs.google.com/spreadsheets/d/1s0pGIM5Vy4CeKIbWnK_5qRYH7nwiLykJXAmawA7Ezd8/edit#gid=0)

**Comment by kcoronel** [comment]
should we create a new project in the repo for the GA sprint?

**Comment by jmensch1** [comment]
Hi @kcoronel, a new project sounds good to me

**Comment by kcoronel** [comment]
Great! I've created a new project and added this issue to it.
