### ISSUE TITLE
Create brigade state adoption interest form 

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#25]
### Overview
We need to create a form to gather information from brigades' interest in helping us with the manual updating process so that when the interface is ready there are people to use it. 

### Action Items
- [x] Define required information
  - [x] Name
  - [x] Email address
  - [x] Location
  - [x] State/county interested in
  - [x] Time available to devote per week before election 
  - [x] How they heard about BallotNav
  - [x] Affiliation
- [x] Contact Jenny Miksell from Food Oasis if there is additional info that should be included 
- [x] Get header image for google form

### Resources/Instructions
- [BallotNav Assets](https://drive.google.com/drive/u/2/folders/1bfDpnAVE5gKNlNiIsVjPsgvKsiSDqV4o)

**Comment by Arjayellis** [comment]
Reached out to Jenny regarding interest form suggestions

**Comment by kcoronel** [comment]
Brigade contact information sheet https://docs.google.com/spreadsheets/d/1jbEHIzEXB5tA4gxtOSz7vDeWeg8ysKpZiDeK1R1fz6g/edit#gid=522188401
Missing states that we would need to recruit externally for: 
American Samoa 
Guam 
Kansas 
Mississippi 
Nebraska 
North Dakota 
Northern Mariana Islands
South Dakota 
U.S. Virgin Islands
West Virginia
Wyoming
