### ISSUE TITLE
Name of responsible official for users EAJ (Back End)

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#254]
### Overview
Users will be able to see the first name and last name of their Election Administration Jurisdiction official. This allows users to have relevant information delivered to them. 

### Acceptance criteria
(how do we know when this task is "Done")
- [ ] search for an address
- [ ] choose a result off the result display 
   - [ ] location details show header 'Your Responsible Official' with the First Name and Last Name of the users EAJ official
- [ ] results match mockups
   - [ ] desktop 
   - [ ] desktop low bandwidth
   - [ ] mobile
   - [ ] mobile low bandwidth
- [ ] Users can see their responsible EAJ official at following locations
   - [ ] Location detail 

### Dependency 
Search by address feature #42 

### Action Items
- [ ] Back End 
  - [ ] AirTable to DB (convert the "State County Locations" table to Postgress)

**Question: we need to confirm developer cadence for updating backend or is it doing it automatically?** (please answer in comment below) 

### Resources/Instructions
[Figma](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=344%3A3232)
EAJ = Election Administration Jurisdiction

**Comment by aNullValue** [comment]
What is the purpose of having the name of the responsible official? It's unlikely that the user would need that name for anything: they would contact the EAJ office rather than a specific person if they need information. Furthermore in some states (many?) the EAJ doesn't have a single official: it's controlled by a board.

**Comment by aNullValue** [comment]
Additionally, there is nothing of interest in AirTable. All useful information regarding EAJs and locations is already in the production PostgreSQL database.
