### ISSUE TITLE
Location Header (Front End)

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#256]
### Overview
We need an area to display the state and EAJ location info. In order to confirm with the user that we are displaying the correct info, and if not, allow them to correct it. 

### Dependency 
feature search by address #42 
invalid address feature #112 
location header (design) #117 

### User Acceptance Criteria 
- [x] Use search by address field to get delivered to a list of ballot drop off sites in user EAJ
   - [x] Enter valid address 
      - [x] see your state at the top of the drop down
      - [x] see your EAJ at the top of your drop down
      - [x] see your EAJ at the top of your drop down,  change it to another EAJ, wipes out previous map 
           - [x] results below (map and location summaries) should change to match what you chose
      - [x] see your state at the top of the drop down, change it to another state, wipes out previous map 
          - [ ] changes the county to the words "Choose your" + ${EAJ} (where EAJ is replaced with the type of EAJ example: city, county, parish, district, etc.)
    - [x] Enter an invalid address 
       - [x] see a dropdown of states and county drop down is hidden.  
       - [x] see search bar again so that you can put in your address again
       - [x] see language where map and locations result normally would be, that instead explains that we could not find your address, and some suggestions for how to format address, or to use the drop downs above.
- [x] Additional test once you have a valid address 
    - [x] click see more info (actual language TBD based on UX writing) 
        - [x] All links should behave according to issue #90 
- [x] Additional test when you have an invalid address 
    - [x] verify you cannot see more info 
- [x] Words that give you drop down (example: Expand to Learn) 
    - [x] Insider of header
    - [x] Links to vote.org and sos (example: We have found the most credible and up to date state and EAJ changes to be on vote.org. Click here to read the current updates for (user state) from vote.org and the SOS. )
    - [x] Notifications Sign- Up (example: get notified of SOS election page changes and vote.org covid19 page changes for your state )
      - [x] error message (search instructions) 

### Action Items
- [ ] Front End 
     - [x] create a valid address view 
     - [x] create an error address view 
     - [x] all links should behave according to issue #90 
     - [x] conditional render of more info when they have a valid State (ex: California) 

### Resources/Instructions
EAJ = Election Administration Jurisdiction 
SOS = Secretary of State

**Comment by adamkendis** [comment]
**Status update on some of the items covered in this ticket:** 

Dropdowns using native select (for mobile) for displayed state and EAJ are working. Working on re-centering the map when an EAJ is manually selected from the dropdowns. Using shapefile here (https://www.weather.gov/source/gis/Shapefiles/County/c_10nv20.zip) that comes with county info including FIPS code and centroid lat/lng.

**Notes/things left to do:** 
  - What to do with really long state names like `Commonwealth of the Northern Mariana Islands`.
  - Determine appropriate zoom level when re-centering map.
  - Fully styled dropdown options for desktop.
  - Move centroid stuff to the backend.
