### ISSUE TITLE
Verification link and phone

### ISSUE THREAD

**Issue by jmensch1** [hackforla/ballotnav#267]
### Overview
We want to display a link and phone number where the user can check the validity of the location information:

![Screen Shot 2020-11-23 at 9 05 23 AM](https://user-images.githubusercontent.com/9143823/99992344-11e67a80-2d6b-11eb-87a4-245194dee874.png)

Currently the back end returns a list of urls and a list of phone numbers for each jurisdiction (and each state) -- not a single link/phone number that the user can use for verification. It's not clear how the front end can figure out which of these urls/phone numbers to display for verification purposes. 

### Action Items

- [x] explore options for identifying a verification link / phone number in the database or in the api layer 
- [x] identify the verification link / phone number in the api response from the get-jurisdiction endpoint

**Comment by aNullValue** [comment]
From a data-intent perspective, it makes sense to me that the URL would be the jurisdiction's URL using urltype.name = 'Jurisdiction Elections Website', which is single-valued. 

For phone numbers, you could filter by phonenumbertype.name = 'Voice' and then take the first result. Or perhaps if there's more than one phone number the UI should be different such that it provides all of the phone numbers. (Particularly if there are multiple voice numbers? Or perhaps if there are multiple numbers of all types for that jurisdiction?)

**Comment by jmensch1** [comment]
Ok, I wonder if we should think about adjusting the Admin client so that volunteers can specifically identify a verification phone/url. It seems pretty important that this detail not get lost/overlooked during the data gathering process. But for now let's see what the GA data looks like adjust our strategy accordingly (I know I keep saying that)
