### ISSUE TITLE
Deduplicate locations by name/lnglat

### ISSUE THREAD

**Issue by jmensch1** [hackforla/ballotnav#268]
### Overview
There are cases where the api returns multiple locations that have the same name and lnglat. For example see "Oriole Park @ Camden Yards" at this search result: 

http://dev.ballotnav.org/map?address=Baltimore%2C%20Maryland%2C%20United%20States&jid=1207&lat=39.2909&lng=-76.6108

![Screen Shot 2020-11-23 at 9 23 27 AM](https://user-images.githubusercontent.com/9143823/99994221-94703980-2d6d-11eb-9796-ff3e1dfcdb83.png)

Notice that the names/addresses are slightly different. But they all show up at the same lng/lat on the map.

### Action Items
- [ ] figure out how to identify duplicate locations in the DB
- [ ] eliminate duplicates from the api response

**Comment by aNullValue** [comment]
This is a bit more complex than just de-duplicating; my knee-jerk response (potentially subject to revision) is that the records in the database aren't actually duplicates, even though it looks like it based on that screenshot. 

- One of them represents two drop boxes that are open continuously between two date/times (that anyone can use?).
- One of them represents an early voting location (with staff that can accept mailed ballots?) that has specific hours prior to election day. (I'm not sure who all can use it during this period, but it may be different from election day.)
- One of them represents an election-day vote center (with staff that can accept mailed ballots?) that has specific hours on election day. (I'm not sure who all can use it during this period, but it may be different from early voting.)

**Comment by jmensch1** [comment]
Ok that makes sense. Let's see if we have similar situations with the GA locations data, and then we can address those individually for now. 

As far as a general solution, it seems like we may need to adjust the UI to draw clearer distinctions between drop-boxes/early voting locations/election-day voting centers. It's a bit confusing right now when they all show up at the same place.

**Comment by kcoronel** [comment]
@jmensch1 is this a good first issue for folks with developer skills? I am cleaning up the board and want to make things easier for folks to get involved in. Thank you!

**Comment by jmensch1** [comment]
@karen, this isn't ready for development yet. First we need to decide whether we're distinguishing between drop boxes/early voting locations/election offices. If we are, then we need to make sure the backend supports the distinction, and figure out how the UI should express the distinction.

**Comment by kcoronel** [comment]
Issue relates to v1 of the project. Currently not pursuing this format of the product. You can find a link to all the issues that have this designation, [here](https://docs.google.com/spreadsheets/d/1ib0z47RjslylwX72FKkA9A07Gu9HkorHEC-b8XOWv5Y/edit#gid=0).
