### ISSUE TITLE
Handle locations that aren't geocoded

### ISSUE THREAD

**Issue by jmensch1** [hackforla/ballotnav#269]
### Overview
Some of the locations are not geocoded, i.e., there's no lng/lat in the api response. In those cases, we can display the location in the list of results, but there's no way to put them on the map. We should figure out how to handle this scenario.

### Action Items

- [ ] Explore methods for geocoding locations that can't be geocoded automatically. Possibly manual searches on google maps. (backend/admin dashboard)
- [ ] Decide how to handle locations that aren't geocoded (frontend/UI/UX)

**Comment by jmensch1** [comment]
This won't be an issue for GA so moving to icebox for now

**Comment by kcoronel** [comment]
@jmensch1 is this a good first issue for folks with UI/developer skills? I am cleaning up the board and want to make things easier for folks to get involved in. Thank you!

**Comment by jmensch1** [comment]
hi @karen, I think we probably need some UI in the volunteer portal where they can find and enter the lng/lat if we don't have one. That's a good first issue for a UI person.

**Comment by kcoronel** [comment]
Issue relates to v1 of the project. Currently not pursuing this format of the product. You can find a link to all the issues that have this designation, [here](https://docs.google.com/spreadsheets/d/1ib0z47RjslylwX72FKkA9A07Gu9HkorHEC-b8XOWv5Y/edit#gid=0).
