### ISSUE TITLE
general issues re: data gathering

### ISSUE THREAD

**Issue by jmensch1** [hackforla/ballotnav#301]
### Overview

We should discuss and create separate tickets for these items:

- We should be careful to use "internalNote", "displayNote", and "rules" for their intended purposes: internalNote should be anything that only we at BallotNav need to be aware of for some reason. displayNote is an arbitrary text field that should be presented to the end-user. rules are supposed to be rules that the voter must comply with before being allowed to enter/use/etc that location.

- During verification, the volunteer should ask staff whether or not the locations/website/etc are relevant for the election we're working on. DeKalb County, in particular, was not even in the vicinity of being correct for the January 2021 special election... its locations seem to have been from the November 2020 general election. But... I wouldn't be surprised if that's because those were on DeKalb's website, represented as "the drop boxes and advance voting locations" without mentioning any election dates.

- If a single location serves multiple functions across different hours, they need to have multiple location records. For example, if an elections office is open mon-fri 8am-5pm, and voters can return absentee ballots to staff during those hours, but they also have an outdoor unmanned drop box open 24/7, we have to use two location records to reflect that.

-  When inputting or verifying addresses, we need to ensure that street post-directionals (i.e., SW, NE, etc) are not made part of the city name. I can't remember which county it was, but one of them was listing addresses as "1 main st, sw atlanta ga 12345"... which made the city in ballotnav be reflected as "sw atlanta"... which is not a valid city, and broke geocoding. i fixed those post-directionals and geocoding worked (at least for the handful i spot-checked).

**Comment by kcoronel** [comment]
Created separate issues for this and they can all be found in Icebox.
