### ISSUE TITLE
Feature Request - Duplicate button on location screen

### ISSUE THREAD

**Issue by aNullValue** [hackforla/ballotnav#333]
As someone who reviews/adds/edits locations within a jurisdiction, and because jurisdictions often have multiple types of ballot returns at a single location, it would be useful to be able to duplicate a location in its entirety. For example, if I open an existing location "Lowndes County Elections & Registration", which is only open Mon-Fri 8am-5pm, I should be able to duplicate it, and then only change the relevant fields to create a new location that's open 24/7 for drop-box purposes.

**Comment by jmensch1** [comment]
closing this because it duplicates #292
