### ISSUE TITLE
User feedback - getting "no results" on mobile is an awful experience

### ISSUE THREAD

**Issue by aNullValue** [hackforla/ballotnav#341]
Currently, if you search for a ZIP code that is not within Georgia, BallotNav will return no results, along with a notice that only Georgia locations are available. That looks perfectly fine on desktop. When you're on mobile though, it just shows you a map, with no pins, and no info about what went wrong. You have to tap "show list" in order to see the notice that there were no results. This is a bad user experience. 

(Comments gathered from friends of @aNullValue 2021-01-05.)

**Comment by Arjayellis** [comment]
@tan-nate @jmensch1 Are we able to display the text on mobile when no results are available?

**Comment by jmensch1** [comment]
yeah I can look at that

**Comment by Arjayellis** [comment]
Thanks dude. I created a bunch of issues last night for basic admin portal fixes and some website changes while we are in this “in-between” phase. Feel free to check them out when you have some time and let me know if you have any questions. 

I also transferred over issues that seemed to be relevant for future elections, so if anything should not be there or if there is something that still needs to be transferred, please let me know. Did the best I could based on what was there.
