### ISSUE TITLE
Identify Next Election

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#353]
### Overview
We need to identify the next election to target. We should make a list of viable options and prioritize based on importance and audience size. 

### Resources
[2021 Elections](https://docs.google.com/spreadsheets/d/1jJJgkNTK0IbUS6gdg_czRf5PUKQbu_gWOjd1aZ4J_e0/edit?usp=sharing)

**Comment by kcoronel** [comment]
**2021 United States House of Representatives elections**
2021 Louisiana's 2nd congressional district special election 20 March 2021
2021 Louisiana's 5th congressional district special election 20 March 2021
2021 New Mexico's 1st congressional district special election March 2021
2021 Ohio's 11th congressional district special election Later in 2021
**2021 United States gubernatorial elections**
2021 New Jersey gubernatorial election 2 November 2021
2021 Virginia gubernatorial election 2 November 2021

**Comment by Arjayellis** [comment]
https://ballotpedia.org/Statewide_elections_calendar#Statewide_elections_calendar

**Comment by allysmatrix** [comment]
Rhode Island on March 2? Their data was well organized - could be a good state to test out our app. https://ballotpedia.org/Statewide_elections_calendar#Statewide_elections_calendar

**Comment by kcoronel** [comment]
@Arjayellis and @allysmatrix do one of you have time to create a spreadsheet to list this information?

**Comment by Arjayellis** [comment]
Another good page that has a list - (https://ballotpedia.org/United_States_municipal_elections,_2021#New_York)

Draft of election selection can be found here (https://docs.google.com/spreadsheets/d/1ab_KXx35b2SVV7K1VQroxiGgNnslQJ7M_Q5cSy-Ah9M/edit?usp=sharing). @kcoronel @allysmatrix  I am not really sure how else to compare them other than timeline and impact/size. I think Virginia, New Jersey, and New York are all good bets.

**Comment by Arjayellis** [comment]
Decision:
New Jersey (general) - Nov 2
Virginia (general) - Nov 2
New Jersey (primary) - Jun 8
Virginia (primary) - Jun 8
New York (general) - June 22
