### ISSUE TITLE
PR Support

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#354]
### Overview
We need to recruit someone who can support PR efforts moving forward and help us reach a broader audience.

**Comment by kcoronel** [comment]
PR Description: [(https://docs.google.com/document/d/1sebY9h7iFwFUtH0PJLm8UNIUY9HPn2bc4dbx3ezxiRk/edit?usp=sharing)]

As of 01.12.20 shared in CFA slack, HackforLA slack and asked Bonnie for other ideas on finding folks to help with this position.

**Comment by Arjayellis** [comment]
Karen spoke to a software engineer with a background in political science/government who we will be speaking to tomorrow afternoon.

**Comment by kcoronel** [comment]
@Arjayellis, @aNullValue and I met with Brian Borin on Sunday January 17. Seems to be more interested in diving into development, reaching out to @jmensch1  to see if there are any immediate needs for developer. Will also send an invite to Brian for Tuesday. 

@Arjayellis - I spoke to Bonnie about our search for someone to help with BallotNav PR. Bonnie believes the new Marketing Community of Practice can be helpful in developing a roadmap for us, and collecting the necessary assets to develop a sustainable and productive PR strategy. We can continue to independently look for a dedicated PR person, but in the meantime, this community of practice can be helpful in laying the groundwork. Please take a look at the [marketing repo] (https://github.com/hackforla/marketing/projects/1) and make suggestions to current checklist (issue #5) and/or any other issue in the repo

**Comment by kcoronel** [comment]
This issue is outdated.
