### ISSUE TITLE
API License 

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#355]
### Overview
We need to explore the possibility and potential benefits of licensing the tool to jurisdictions to use as they see fit. This would remove the need for us to validate the data each election and take off some of the risks.

**Comment by Arjayellis** [comment]
Potential models:
1.Do what we are doing now 
2. Potentially packaging the entire app up and doing automation so that each jurisdiction can add and manage the data/process themselves
3. Do what we do no, but allow govt to provide data
4. Become API that potentially runs widgets on their website

Need to consider ramifications:
1. Software publishing (easiest, but not sure if people will be on board) - need to make sure it's well put together and easy to deploy 
2. If we still host data and become a service provider - we would need to make sure we are ready to support that. Official election product that needs to be supported, we need to be able to scale up quickly

**Comment by kcoronel** [comment]
Great idea! I think packaging the app will be extremely helpful, even if we can't get it to government (state's board of election) we can give it to an organization working on voter engagement.

**Comment by kcoronel** [comment]
Decision was shared within MVP document found in google drive.
