### ISSUE TITLE
Non Partisan Partners

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#361]
### Overview 
Find potential non partisan partners that can benefit from BallotNav product. 

### Related Issues 
#405 #406 

### Action Items 
- [x] Search the web for non-partisan organizations working towards making voting easier and note them in excel sheet

### Resources 
[Ballot Nav Potential Partners](https://docs.google.com/spreadsheets/d/1G42xVXKWNxcy2oOi2uBCtfIKyE4yUqp703vCKbE3I8Y/edit?usp=sharing)

**Comment by kcoronel** [comment]
@Arjayellis @allysmatrix I utilized our analysis matrix to create our [Potential Partners] (https://docs.google.com/spreadsheets/d/1G42xVXKWNxcy2oOi2uBCtfIKyE4yUqp703vCKbE3I8Y/edit#gid=0) workbook. 
At this moment it has a few partner organizations that are non-partisan and work on engaging voters/voter access. This can be a project we engage other folks into?

**Comment by Arjayellis** [comment]
@kcoronel @allysmatrix Are one of you able to start on this?

**Comment by kcoronel** [comment]
I'll assign myself this and work on getting something for the next mtg.

**Comment by kcoronel** [comment]
@Arjayellis @allysmatrix I've found a couple of organizations, and a bit stuck on what is the next course of action. Below I've outlined some ideas that we can discuss. 

1/ Outline the key benefits organizations will receive by partnering with BallotNav 
2/ Should I explore organizations that fund data science/democracy problem solving?

**Comment by kcoronel** [comment]
@kcoronel ^^ reminder from above

**Comment by kcoronel** [comment]
In response to above. The research was a good starting point to kick start us in our journey of choosing what came next for BallotNav. 

Closing this issue because work associated with this issue was completed.
