### ISSUE TITLE
BallotNav Product Demo Video

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#364]
### Overview 
Due to the amount of data our project requires (we have collected data for jurisdictions across the 50 states), our AWS usage cost has been high. In order to reduce costs for our project and prepare for pitching to partner or governmental organizations, we decided to design and develop a demo site that can be hosted on github. 

### Action Items 
- [x] Provide designers with direction for what is needed for demo video
- [x] Approve designs and coordinate with development for building site 

### Resources/Instructions 
[Figma](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=1313%3A56178) Under pages click BallotNav and scroll down to 1.27.2021 
[Demo Video](https://hackforla.slack.com/files/U01A3MMN59U/F01SA448P5L/ballotnav03.mp4)

**Comment by kcoronel** [comment]
Message from @fedelandini "In our shared Figma file you can see a  proposal for the Demo label, in different color versions. We think the most consistent and easy solution would be to keep the warning strip that we already have, as an area dedicated for any important information. We can customise it, according with the message. So we can change the color, make it permanent, or expandable. In this specific case we have removed the X."

**Comment by kcoronel** [comment]
I think the color red stands out the most, but I think we want to try and stick with not using either red or blue on their own. Perhaps trying a yellow or orange warning strip might work? I am also aware that it can clash with our existing colors. For example, the blue gets lost with our own blue. 

I think we may also have to add some language that pops up above or below the Search Location Box - This demo is utilizing information validated for the 2021 Georgia Special Election, within the search location box it should say Georgia right now it says Los Angeles

**Comment by kcoronel** [comment]
Some comments from our team meeting 2/2/21 
+ Font bigger & centered 
+ between yellow and orange

**Comment by kcoronel** [comment]
@fedelandini @IrinaRost when you have a time, please add updates to this repo. Jake mentioned that you were doing some user-testing, where are we with this? Thank you!

**Comment by kcoronel** [comment]
Video from @IrinaRost @fedelandini https://youtu.be/jGvLMrF9O9w

**Comment by fedelandini** [comment]
Hi @kcoronel thanks for the feedback, we'll fix it ASAP

**Comment by kcoronel** [comment]
Edited video https://hackforla.slack.com/files/U01A3MMN59U/F01SA448P5L/ballotnav03.mp4 @allysmatrix @Arjayellis please let us know if there are any edits

**Comment by ExperimentsInHonesty** [comment]
Please say election jurisdiction instead of county - you will probably have to explain it (in your state this can be county, town, parish, etc.)

**Comment by kcoronel** [comment]
Currently asking BallotNav team to make edits in this issue.

**Comment by kcoronel** [comment]
My comment would be to not cover the face of the model for the introduction pages. To Bonnie's comment, perhaps there can be an introduction page with what an election jurisdiction means.

**Comment by aNullValue** [comment]
I'd be more inclined to stick with county, or maybe "county or municipality". Introducing the concept of EAJ to the public seems like a bit much to me, given that the average voter would likely never encounter that terminology in the course of voting.

I really like the video overall. Improvements that could be made in the future: 

* using a version of the app that doesn't include the demo warning banner
* some locations should be open rather than everything closed 
* the procedure for browsing by jurisdiction makes me... uneasy. Technically there's no way to search for a jurisdiction; you're always searching for an address that will be geolocated into a jurisdiction, and then you can change which is displayed. 

(Yes, the demo app will need improvement in order to make this feasible.)
