### ISSUE TITLE
Create About page

### ISSUE THREAD

**Issue by jmensch1** [hackforla/ballotnav#366]
### Overview

We need to implement the landing page for our [about](https://about.ballotnav.org) site, which is currently just a stub.

The designs are at the bottom of the "Ballotnav" page of this figma file, next to a label that says "04.08.21 Landing Page: Final"
https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=2848%3A8580

To start development:
1. pull the latest code from `master`
2. run `npm run start-about` from the `client/web` directory. This will open the about app in a browser.
3. The Landing page component is at `src/components/pages/Landing.js`

### Action Items

- [ ] Implement the figma design for the Landing page
- [ ] We don't have separate designs for mobile, but the page should still look reasonably good on a phone.
- [ ] Keep the code files short and tight. All submitted code files should be less than 100 lines.
- [ ] When you're done, run `npm run lint` to format your code. Then commit any changes that the linter makes.
- [ ] Submit a PR

**Comment by jmensch1** [comment]
note that we're still waiting on confirmation of which design we're using

**Comment by kcoronel** [comment]
@jmensch1 @alligatormonday I've moved this issue to 'Prioritized Backlog' as we wait for the final designs to be submitted from ui/ux team

**Comment by jmensch1** [comment]
moving this to in progress @alligatormonday it's on!

**Comment by alligatormonday** [comment]
04/13/2021 Update: 

Starting working on the landing page. In progress. No roadbloacks. Need more time.

**Comment by alligatormonday** [comment]
04/20/2021 Update: 

Landing page components have been created. The only thing remaining is styling.

**Comment by alligatormonday** [comment]
04/26/2021 Update: 

Need help with styling.

**Comment by kcoronel** [comment]
Jake and Joseph will schedule a mtg. re: styling

**Comment by alligatormonday** [comment]
05/04/2021 Update: 

Need to make the final touches. Have a question regarding one of the logos/images. Will address in the meeting.

**Comment by alligatormonday** [comment]
PR made. Ticket Complete!
