### ISSUE TITLE
Call Secretary of State Office in NJ, VA, and NY 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#373]
### Overview
We want to give the Secretary of State (SoS) office and introduce ourselves to call and inquire about their election process for June. 

### Action Items
- [ ] Each PM calls one SoS office and details call in this issue 
- [ ] Questions to ask: 
  - [ ] New York (Karen)
     - [ ] When does the state plan on releasing ballot drop box locations for your (insert June election date) 
     - [ ] Do you plan to release a list of drop-box location or will it be a gradual process? 
  - [ ] New Jersey (Randall)
     - [ ] When does the state plan on releasing ballot drop box locations for your (insert June election date) 
     - [ ] Do you plan to release a list of drop-box location or will it be a gradual process?
  - [ ] Virginia (Alina)
     - [ ] When does the state plan on releasing ballot drop box locations for your (insert June election date) 
     - [ ] Do you plan to release a list of drop-box location or will it be a gradual process? 
    
### Resources/Instructions

**Comment by kcoronel** [comment]
Called NY BOE (518) 474-6220 and got a VM

**Comment by kcoronel** [comment]
@allysmatrix @Arjayellis Please provide update
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by Arjayellis** [comment]
@kcoronel this completely slipped my mind. I will take care of it tomorrow. Are you referring to what challenges I ran into and when I can discuss when you say blockers and availability?

**Comment by Arjayellis** [comment]
@kcoronel @allysmatrix Spoke to rep at the NJ office and she said that they will likely be using the same locations as those that were used for the presidential election last year. Moving forward, these will most likely turn into permanent locations. 

She doesn't have any additional information in terms of when the data will be released. Will have to check back in closer to June.

**Comment by kcoronel** [comment]
@kcoronel @allysmatrix please provide update
1. Progress  so far 
2. Any roadblocks? 
3. Availability  to complete issue 
4. ETA for issue to be completed

**Comment by allysmatrix** [comment]
Called VA at (804) 864-8901 and got a VM, an left a voicemail (on

**Comment by kcoronel** [comment]
Called SOS of NY 4/6 and was told that they are considering a smaller sample size of locations directly accepting mail-in ballots as they have early voting in place and Rank Choice Voting as an option. I mentioned that I would call bi-weekly to check on status and hopefully get data from their team.
