### ISSUE TITLE
Increase ratio of image on hackforla.org project page for BallotNav to 3:2

### ISSUE THREAD

**Issue by shaswa** [hackforla/ballotnav#380]
### Overview
All  project images on the [hackforla homepage projects section](https://www.hackforla.org/#projects) should have a 3:2 ratio and a standard resolution of 600x400 pixels or higher. 

Current Resolution: 597 x 400 pixels
Current Ratio: 2.985:2

### Action Items

- [ ] Increase ratio of project image for BallotNav to 3:2
- [ ] Increase resolution of project image for BallotNav to 600 x 400 pixels or higher
- [ ] Update Status on hackforla/website#1105

### Resources/Instructions
[Projects page](https://www.hackforla.org/#projects)

**Comment by kcoronel** [comment]
@shaswa thanks for sending this to us, question, can we update our images to the correct resolution and pixels on photoshop or is it better to find new images for BallotNav 

Thank you!

**Comment by shaswa** [comment]
@kcoronel I think it's better to update it via photoshop as you just need to increase the length by 3px

**Comment by shaswa** [comment]
@kcoronel [Here](https://www.hackforla.org/assets/images/projects/ballot-nav.png) is the URL of the current image that needs to be updated.

**Comment by kcoronel** [comment]
@shaswa let me know if this works, thank you! 
![BallotNav_1](https://user-images.githubusercontent.com/38144130/112871443-1fdb3d80-9074-11eb-8838-a98019b7da2b.png)

**Comment by kcoronel** [comment]
@shaswa can you let me know the status for this, thanks!

**Comment by kcoronel** [comment]
Hi @shaswa is this complete? I would like to clean up the issues I am tagged in. TY!

**Comment by kcoronel** [comment]
@shaswa checking in on the status of this. TY!
