### ISSUE TITLE
DNS for BallotNav

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/ballotnav#381]
### Overview
We need to point the DNS for BallotNav at a variety of locations so that we control what people see when

### Action Items
- [x] get control of the domain name
- [x] Point the dns at the locations provided by Drew

**Comment by aNullValue** [comment]
<img width="460" alt="Screen Shot 2021-03-02 at 09 55 55" src="https://user-images.githubusercontent.com/3424516/110559858-fc773f80-8112-11eb-8560-ec1c35515405.png">

**Comment by ExperimentsInHonesty** [comment]
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

**Comment by jmensch1** [comment]
I was able to hook this up through AWS, using CNAME records for `about.ballotnav.org` and `demo.ballotnav.org`, and an A record for `ballotnav.org`.
