### ISSUE TITLE
Scrape VA data for the upcoming June Elections

### ISSUE THREAD

**Issue by allysmatrix** [hackforla/ballotnav#383]
### Overview
We don't know the timeline for states to release ballot drop box locations, and since beginning BallotNav for the general election, we know we have a three-week cushion to upload data to BallotNav and validate.

In an effort to gather useful data before the June election. BallotNav wants to scrape VA data ahead of time. 

### Action Items
- [ ] Scrape data 
- [ ] Review data with BallotNav team and determine finalized features 

### Resources/Instructions
Finalized features for BallotNav 2021

**Comment by kcoronel** [comment]
Please provide update
1. Progress so far
2. Any roadblocks?
3. Availability to complete issue
4. ETA for issue to be completed

**Comment by allysmatrix** [comment]
I plan to get the scrape done before the end of April.
