### ISSUE TITLE
Scrape NY data for the upcoming June Elections

### ISSUE THREAD

**Issue by allysmatrix** [hackforla/ballotnav#384]
### Overview
We don't know the timeline for states to release ballot drop box locations, and since beginning BallotNav for the general election, we know we have a three-week cushion to upload data to BallotNav and validate.

In an effort to gather useful data before the June election. BallotNav wants to scrape NY data ahead of time. 

### Action Items
- [ ] Scrape data 
- [ ] Review data with BallotNav team and determine finalized features 

### Resources/Instructions
Finalized features for BallotNav 2021

**Comment by giosce** [comment]
It seems to me that NY didn't have pure ballot dropbox in 2020, 
https://www.ny.gov/early-voting-and-absentee-voting-mail-or-dropbox
Not really true, we need to go through the main page links to counties website and some of them have a bunch of locations.

**Comment by giosce** [comment]
It can be useful to see the NY data currently in the system if any (@aNullValue)
