### ISSUE TITLE
Update BallotNav HackforLA Site 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#386]
### Overview
Updating the site so that we can better represent the status of the project and those working on it. 

### Action Items
- [ ] Update Open Roles 
- [ ] Update Project Leadership 
- [ ] Update Contributors

**Comment by kcoronel** [comment]
**Open Roles:** 
Marketing & PR 
Partnerships & Fundraising
Validator Volunteer Leads 

**Project Leadership**
Karen Coronel - PM 
Randall Ellis - PM 
Alina Shokina - PM/Data Scientist 
Andrew 'Drew' Stemen - Developer 
Jake Mensch - Developer 
Irina Rostovtseva - UI/UX Designer 
Federica Landini - UI/UX Designer

**Comment by kcoronel** [comment]
@Arjayellis let me know if I missed anything. Thank you!

**Comment by Arjayellis** [comment]
@kcoronel Looks good. @aNullValue did you want to be called something else? Like "Master of Numbers"?

**Comment by BrianCodes33** [comment]
What is this? We are all leaders.

**Comment by kcoronel** [comment]
Outdated request.
