### ISSUE TITLE
Increase ratio of image on hackforla.org project page for BallotNav to 3:2

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#389]
### Overview
This is an[ issue ](https://github.com/hackforla/ballotnav/issues/380#issue-820489620)from our marketing team
All  project images on the [hackforla homepage projects section](https://www.hackforla.org/#projects) should have a 3:2 ratio and a standard resolution of 600x400 pixels or higher. 

Current Resolution: 597 x 400 pixels
Current Ratio: 2.985:2

### Action Items
- [ ] Increase ratio of project image for BallotNav to 3:2
- [ ] Increase resolution of project image for BallotNav to 600 x 400 pixels or higher
- [ ] Update Status on hackforla/website#1105
- [ ] Add new edited image to [folder](https://drive.google.com/drive/folders/1kMR8vofBYSEsNEckOFCt85N0GTo6H5d8?usp=sharing)

### Resources/Instructions
[Image that needs to be changed](https://drive.google.com/drive/folders/1kMR8vofBYSEsNEckOFCt85N0GTo6H5d8?usp=sharing)
[Projects page](https://www.hackforla.org/#projects)

**Comment by kcoronel** [comment]
You can take the logo and create a white canvas that is 600x400 and then move the logo onto it reducing its size.

**Comment by AshishRajIITI** [comment]
Hello @kcoronel, I am beginning my open source contribution journey. I have good knowledge of HTML, CSS, Javascript. So if u can assign this issue to me, I would be highly grateful. I am confident that I can resolve this issue with ease. Please provide me access to all the resources since I can't open them now. (I have requested access to the drive link) Thank You :)

**Comment by kcoronel** [comment]
@AshishRajIITI wondering if you went through HackforLA's onboarding training? Checking as this is part of our onboarding process. Thanks!

**Comment by kcoronel** [comment]
@jonlam27 can you let me know if this is an okay issue to assign to you. Thanks!

**Comment by jonlam27** [comment]
@kcoronel Hey sorry Karen, unfortunately, I'm not too familiar with this. I suppose it might have to do with resizing via html?

**Comment by kcoronel** [comment]
![BallotNav_1](https://user-images.githubusercontent.com/38144130/112870972-a5122280-9073-11eb-89ca-68ca3ff8c476.png)

**Comment by kcoronel** [comment]
@fedelandini I sent the image above over to our marketing team so will let you know if we need to resize but I think this is okay

**Comment by fedelandini** [comment]
Hi @kcoronel I resized the image to 600X400 and saved in our shared folder ballotnav-pr-image-web_600x400.jpg https://drive.google.com/file/d/1yYZTby0utqgrFLBcTrRXqu19HPPJHgCV/view?usp=sharing

**Comment by RobertaFricker** [comment]
I deleted the previous image: ballot-nav.png and changed it to: ballotnav.jpg, the image one shown in Issue #1341.
It is now 600 x 400 and here's a screenshot from Paint:

![image](https://user-images.githubusercontent.com/81199122/114477547-32e02880-9bb1-11eb-901b-6a3073711bdf.png)

I submitted a Pull Request 4/12/21.  Please advise if you need any further update status, I'm new...; )...thanks.
