### ISSUE TITLE
Create a wiki for our project 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#396]
### Overview
The marketing team audited our project and recommended we have a wiki for amplification of our project. 

### Action Items
- [x] Take inventory of other projects wiki 
- [x] Draft a BallotNav wiki 
- [x] Review BallotNav wiki with team 
- [x] Upload BallotNav wiki 

### Resources/Instructions
[Wiki DRAFT](https://github.com/hackforla/ballotnav/wiki/Welcome-to-BallotNav!)

**Comment by Arjayellis** [comment]
@kcoronel @allysmatrix please check it out and let me know what you think. This can be a dynamic page, so I am just thinking as a starter wiki. https://github.com/hackforla/ballotnav/wiki/Welcome-to-BallotNav!

**Comment by kcoronel** [comment]
@Arjayellis it looks great! I think we can try and get our demo to be non-static on the page?

**Comment by Arjayellis** [comment]
Would you clarify what you mean @kcoronel? I am just providing links to various resources for new volunteers to reference.

**Comment by kcoronel** [comment]
you mentioned it could be a dynamic page, I thought you meant perhaps embedding our product within the wiki. I looked at VRMS' wiki and it didn't seem much more dynamic than ours, so I think we are on the right track.

**Comment by Arjayellis** [comment]
I mean dynamic in that we can continue to update it, not the actual page being able to move lol
