### ISSUE TITLE
Team Information for Website

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#398]
### Overview
We need to collect all team member's Name, slack ID, github ID, and role so we can add everyone to the Hack for LA website. 

### Action Items
- [ ] Each member needs to post the above information in a comment below.

**Comment by kcoronel** [comment]
Karen Coronel, U010KUGJATC, kcoronel, Product Manager

**Comment by alligatormonday** [comment]
Joseph Jepson

- Slack ID: U01S5QUQ2FK
- GitHub ID: alligatormonday
- Junior Developer

**Comment by kcoronel** [comment]
This request is outdated.
