### ISSUE TITLE
Create a clickable prototype for BallotNav 

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#407]
### Overview
We need to create a clickable walkthrough prototype for the project so people can view at their own pace in an easy to view way

### Action Items
- [x] Design prototype
- [x] Review with team
- [x] Add to wiki

### Resources/Instructions
[Figma](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=264%3A3)
[VRMS example](https://www.figma.com/proto/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25555%3A80&viewport=617%2C535%2C0.06256388127803802&scaling=min-zoom)

### Parent Issue
#403

**Comment by kcoronel** [comment]
Questions: What is the goal of the task? Do we want this to be fully clickable?

**Comment by Arjayellis** [comment]
@IrinaRost @kcoronel 

- The goal is to give users/investors/partners a way to visualize the app experience and travel through the mobile process at their own pace. 
- Does not need to be fully clickable, just a representation. Please see the example provided in the resources section above

**Comment by IrinaRost** [comment]
Link to the [mobile vrsion prototype](https://www.figma.com/proto/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=3719%3A13582&scaling=scale-down&page-id=3719%3A11979)

**Comment by kcoronel** [comment]
@Arjayellis this is in review for you to look over

**Comment by Arjayellis** [comment]
This looks good to me. @kcoronel @allysmatrix please let me know if you both approve.

**Comment by kcoronel** [comment]
Fundraising ask; clickable prototype of app, what was need when we have demo application - notes from Team meeting on 8/30 
@Arjayellis can you give us some more insight about why this prototype was needed
