### ISSUE TITLE
Update Product Roadmap

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#409]
### Overview
We need to update the product roadmap to reflect recent developments and ensure we are on track

### Action Items
- [ ] Create draft
- [ ] Approval by team
- [ ] Add to wiki

### Resources/Instructions
[Current Roadmap](https://docs.google.com/spreadsheets/d/1vVo87ZO02xd_JyLDXDm6Q5EWRGKRzsl6Nj_Gt8Wl3wc/edit#gid=961494988)
[VRMS example](https://docs.google.com/document/d/1BlhtbYBbSBlwSKNFupqUwdtKiUluCErIt0Mr4vNzxlA/edit)
[311 example](https://docs.google.com/spreadsheets/d/1TipvVwhifg9vFwaLBvJJRC6B2Kpjj1AULDGl5hWVV2o/edit#gid=0)
Parent Issue - #403

**Comment by kcoronel** [comment]
Closed because this issue was duplicated and outdated.
