### ISSUE TITLE
AirTable fixes

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/ballotnav#41]
### Overview
we need to fix a few minor problems in AirTable so that the forms work properly on Saturday 9/12/2020 National Day of Civic Hacking

### Items
- [x]  Claim a state lets you claim a state that is already claimed
- [x]  Amazing Scrapers page does not show the url of the people who have claimed the state to scrape

### Resources/Instructions
[Link to contributing doc to check flow](https://docs.google.com/document/d/1gsvoKcn3j9CaJbzxkc52ONB0HudmEq-QgV8Xps2If1g/edit#heading=h.o5oxxv5jy2ww)

Users that we created for testing purposes
- Super McFly
- Happy Golucky

**Comment by Arjayellis** [comment]
![Screen Shot 2020-09-12 at 1 15 32 AM](https://user-images.githubusercontent.com/69663209/92991024-89f41280-f495-11ea-926f-d02b49d96982.png)
