### ISSUE TITLE
feature: search by address

### ISSUE THREAD

**Issue by jafow** [hackforla/ballotnav#42]
### Overview

a user needs to be able to enter an address and receive information about their closest ballot dropoff location. 

### Acceptance criteria
(how do we know when this task is "Done")
- [ ] Use Input bar to get delivered to a list of ballot drop off sites in your EAJ
   - [ ] enter a valid Zip Code 
   - [ ] enter a valid City and State
   - [ ] enter a full address
   - [ ] choose "Current Location"
- [ ] results match mockups
   - [ ] desktop 
   - [ ] desktop low bandwidth
   - [ ] mobile
   - [ ] mobile low bandwidth
- [ ] If view includes map
   - [ ] pins are representative of locations within your EAJ and you can click on them to see location detail. 

Users can search at following locations
- [ ] Homepage
- [ ] Search Results page

Users can search the followings ways
- [ ] By Current Location
- [ ] By Full Address (e.g., 13428 Maxella Avenue, Marina Del Rey, CA 90292)
- [ ] By City and State
- [ ] By Zip Code

Error Handling requirements
This has an issue Invalid Address Feature  #112 
- [ ] If null value or error is returned by API user is delivered to Search Results view with no map and no results and a message where those would normally be indicating that they should choose their state from the drop down and then their EAJ.  Also present search bar again so that they can put their address in again. 

### Action Items
Search (using interface code from FoodOasis for the search)
- [x] Product
   - [x] Identify criteria for ways they can search
   - [x] Identify locations for search bar
   - [x] Identify error handling requirements
- [ ] UI/UX
   - [ ] Search bar should appear in identified locations
   - [ ] Make mockup with Error Handling view
- [ ] Font End Dev (React)
   - [ ] Build out homepage according to design spec
- [ ] Back End
   - [ ] AirTable to DB (convert the "State County Locations" table to Postgress)
  - [ ] api to send user input (from home page) and get back EAJ info, so that front end can route search results page view
- [ ] Front End integrator
   - [ ] integrate api into search

### Resources/Instructions
[foodoasis.la search example](http://foodoasis.la)
[Figma](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=344%3A3232)
EAJ = Election Administration Jurisdiction

**Comment by geleazar1000111** [comment]
interested in working on this and issue [47](https://github.com/hackforla/ballotnav/issues/47)
