### ISSUE TITLE
Make Demo Site Arrow Links Work 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#426]
### Overview
When you walk through the BallotNav demo, there are a few sites we link to _(screenshot below)_ that aren't clickable. 

### Action Items
- [x] Make links clickable 
- [x] Comment below when issue has been solved 

### Resources/Instructions
<img width="506" alt="BallotNav" src="https://user-images.githubusercontent.com/38144130/120950000-b1150300-c6fa-11eb-9afd-187b26709897.png">

**Comment by jmensch1** [comment]
This is fixed.
