### ISSUE TITLE
Create a citizen to citizen symbol / verbiage 

### ISSUE THREAD

**Issue by allysmatrix** [hackforla/ballotnav#427]
### Overview
Create a **citizen to citizen** symbol / verbiage and add it to either about page or every page of this site. This would highlight the nature of this project as a citizen to citizen project, with the main goal of helping each other. This would also help build BallotNav brand identity.

### Action Items
- [ ] Discuss the verbiage ideas with the PM team
- [ ] Discuss the design ideas with the UI/UX team
- [ ] Add verbiage and design to Figma 
- [ ] Assign issue to front end team 
- [ ] Front end team makes edits 
- [ ] Comments below that edits are complete

### Resources/Instructions

**Comment by kcoronel** [comment]
This issue will be replaced by 2022 branding/brand identity and project North Star.
