### ISSUE TITLE
BallotNav Next MVP Proposal

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#430]
### Overview
In order to determine how to best move forward with BallotNav for the 2022 midterm elections, our team decided to write out options for Bonnie to review 

### Action Items
- [ ] 

### Resources/Instructions
[BallotNav Next MVP Proposal](https://docs.google.com/document/d/1TTQUDNSttQs1HU5z4IM9SIXeGvtCL_kJyiXZ2O4lkKE/edit?usp=sharing)

**Comment by kcoronel** [comment]
Completed.

**Comment by staceyrebekahscott** [comment]
Closing this issue as a more current issue, #447 has been created. Comment above by Karen noted that issue was completed and moved to Done board, but it was not fully closed.
