### ISSUE TITLE
BallotNav Communications Guide

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#435]
### Overview
BallotNav is missing a Communications Guide that helps coordinate the creation of a visual framework for the consistency of training and educational materials across the BallotNav volunteer teams. 

The Communications Guide in this context means a presentation template which includes logos and formatting for slide decks, docs, and sheets to be used whether the it is for internal or external use.  All slide decks, docs and sheets should follow this template. 

### Action Items
- [x] Review resources in issue [Create a Guide: Communication (style) Guide for Document Creation - Gather Hack for LA examples](https://github.com/hackforla/product-management/issues/278#issue-957052416)
- [x] Draft Communications Guide for BallotNav 
     - [ ] Review between UI/UX team 
- [ ] Update issue [Create a Guide: Communication (style) Guide for Document Creation - Gather Hack for LA examples](https://github.com/hackforla/product-management/issues/278#issue-957052416) by 
     - [ ] placing a link to BallotNav Communication Guide in the issue summary 
     - [ ] comment in issue asking for peer review 

### Resources/Instructions
[BallotNav Communication Guide](https://drive.google.com/drive/folders/1mJy2iq0pBxcsCuEdAl3d1_nlXLwiNdvE)

**Comment by kcoronel** [comment]
@fedelandini @IrinaRost

**Comment by kcoronel** [comment]
@jonlam27 great work! I updated the issue above to reflect the next steps we spoke about at our meeting. Fill free to edit as needed.

**Comment by kcoronel** [comment]
@fedelandini @IrinaRost please review BallotNav Communications Guide; please make sure your complete names and Jon's are the first three on the slide deck

**Comment by kcoronel** [comment]
Checking format of banner and design system edits within the presentation

**Comment by kcoronel** [comment]
Working on design system to link everything to the guidelines, and the complete library for BallotNav.

**Comment by kcoronel** [comment]
Update: will look to have it done next week.

**Comment by staceyrebekahscott** [comment]
@IrinaRost @fedelandini Please add update on the current status of this issue. Is it near completion? If not, given our current scope and priority of research for the Board of Advisors, we should consider moving this to the prioritized backlog for now. But if it can be completed within 1-2 weeks, we should work to get it done and closed out.

**Comment by staceyrebekahscott** [comment]
- Removed assignees- Federica and Irina
- Notified assignees that they have been removed from issue
- Determined that this issue is not relevant to the current direction of BallotNav and should not be In Progress
- Moved to Ice Box

**Comment by staceyrebekahscott** [comment]
@fedelandini @IrinaRost Removing your assignment from this issue, as it does not pertain to the current direction of the project.

**Comment by staceyrebekahscott** [comment]
@ExperimentsInHonesty It was unclear to me what this issue was for, as the term "communications guide" is somewhat ill defined in this context. 

I have included this definition the Overview section above: 

The Communications Guide in this context means a presentation template which includes logos and formatting for slide decks, to be used whether the deck is for internal or external use.  All slide decks created for BallotNav should follow this template. 

There has been no Product Management Community of Practice since I joined Hack for LA, so I am figuring things out without much guidance.  I appreciate you bringing this to my attention and will address the formatting for the slide decks from their respective issues.

**Comment by staceyrebekahscott** [comment]
Reopened and reassigned issues #487 and #486 and updated issues #488 and #445 to update the slide decks to match the formatting dictated by the BallotNav Communications Guide.

**Comment by staceyrebekahscott** [comment]
Documentation for issue #486 has been updated to match the communications guide templates.

**Comment by staceyrebekahscott** [comment]
@jonlam27 I am assigning this to you. Maybe we can have a chat about this sometime soon. I'd like to get a better understanding of the designs and what needs to be completed.

**Comment by staceyrebekahscott** [comment]
@jonlam27 Following up on this: are you able to summarize what you feel needs to be done on these templates?

**Comment by jonlam27** [comment]
Hey @staceyrebekahscott, sure thing.

- There wasn't a whole lot of feedback on the template itself when it was created so it would be great to get some input on how everything is structured and the overall look and feel.
- the work for the template stopped as I was trying to find a suitable banner for the google forms template - the images in the figma file weren't the right dimensions so I looped in the design team to help with that - unsure if we now have a banner?
- the existing structure of the guide was based on [BOP's](https://docs.google.com/presentation/d/1uIRCQXKmOYifAhGOQArK0JMmlksE7U4KvuMN0Be11-0/edit?usp=sharing). Within it an airtable template was included - do we see a need to also use airtable and/or are there other document creation software or programs that we should include here?

**Comment by staceyrebekahscott** [comment]
@jonlam27 I think for the documentation we are creating, the graphics are fine for now. As we are now researching a new direction for the project and may need to redesign all of the graphics, I no longer think working on the current set is the best use of our time. If we create something and need a graphic that is not quite right, we will address it at that time.  I'll remove your assignment and close the issue.
