### ISSUE TITLE
BallotNav 2022 PM Roles and Responsibilities 

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/ballotnav#451]
### Overview
As of February 2022, we have a team of 5 PM's. In order to make this the best learning and skill building experience, we have decided to divide our responsibilities by the following. 

Don't know where to add this 
- [ ] Team Agenda creation 
- [ ] Send minutes to team slack account 
- [ ] Remind team members to update issues
- [ ] Approval of New Issue Request from non-PM team members 
- [ ] Attend CoP meetings on behalf of BallotNav 
- [ ] Managing Kanban board 

## Administrative PM 
- [ ] Onboard new team members
      - [ ] Ask new member for their email and share team roster    
      - [ ] Ask new member for their email and share team roster
      - [ ] Add new team members to Google Drive 
      - [ ] Request team members be added to the repository in #admin slack channel 
      - [ ] Confirm team member has 2factor authentication on 
       - [ ] Invite new team members to 1Password
- [ ] Create team Zoom account and add login information to 1Password 
- [ ] Monitor inbox 
- [ ] Manage the update of Wiki Page 
- [ ] Update project one sheet 

## Technical PM 
- [ ] Host meetings with development team 
- [ ] Responsible for monitories issues with the tag role: backend, role: frontend 
- [ ] Post openings in Engineering CoP 
- [ ] work with engineering team for PRD and functions document 
- [ ] Product Roadmap (can be shared with below outline) 

## PM 
- [ ] Lead new initiatives from HackforLA re: brand book 
- [ ] Lead OKR and North Star development 
- [ ] Onboarding documents and slide deck (shared with admin PM) 

## Partnership PM 
- [ ] Responsible for organizing all internal and external partnership documentation (ex: slide deck presentation, project journey presentation, clickable prototype) 
- [ ] Responsible for managing communication with partners (this will be a shared responsibility with Admin) 
- [ ] Responsible for updating team

**Comment by kcoronel** [comment]
@staceyrebekahscott @yoursgayathri @layneam @pguron - please review and add any additional comments

**Comment by staceyrebekahscott** [comment]
Of the tasks that need to be assigned to a role: 

These should go under the Admin PM role:
- Team Agenda creation
- Send minutes to team slack account
- Approval of New Issue Request from non-PM team members

These should go under PM role (should we call it General PM?)
- Remind team members to update issues
- Attend CoP meetings on behalf of BallotNav
- Managing Kanban board


Another item to discuss would be how long any one of us should hold each role. The intention here was to create these roles and then rotate so we can each learn how each one works, and give us an opportunity to work more closely with team members from different departments. 

Suggested time: 3 months per role, then we can decide if we should continue as is, or if some or all of us should rotate a role. 

Perhaps it would be best to take on a role that most fits a current skill set to start, and then move on to one where there is more of a learning curve. 

I would like to suggest myself to take on the PM (general PM?) role at this time, with the team's approval. It fits my skill set and relates to some of the issues I am assigned to at this time.

**Comment by kcoronel** [comment]
I like your additions and describing it as General PM, I feel as if 3 months might be too long BUT then I realize our meeting schedule is like, so it does seem like an appropriate amount of time.

**Comment by kcoronel** [comment]
@yoursgayathri @layneam please add any edits/suggestions/etc. we can chat about it next week.

**Comment by staceyrebekahscott** [comment]
[HfLA Role Definitions](https://docs.google.com/document/d/1X6d6-Sm_QDQPobiRfqachCSajAOpqRLVUsdCnczhhts/edit#)

**Comment by kcoronel** [comment]
closing this issue because we have stepped away from this model of splitting the PMs into 4 different tracks.
