### ISSUE TITLE
02/11/22 Agenda for PM Pre-Onboarding 

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/ballotnav#452]
02/11/22 Agenda for PM Pre-Onboarding 

### Roll Call
Karen
Stacey
Layne
Punit
Gayathri

#### **Priority Items**
Welcome to BallotNav and Roadmap Review: 
- Intro to the BallotNav project for new PMs
- Brief overview of Roadmap

Review New Issue Approval list:
- Issues pulled from Icebox and Prioritized Backlog to gain a sense of current work to be assigned to PMs. 

Review and Clean Up of the Kanban Board:
- Will spend time after the Pre-Onboarding meeting to clean up Kanban. 
- Need to complete this before creating new issues from Roadmap. 

Create New Issue Demo:
- Create a new issue to create a Kickoff Deck for new team members.
    - Details on the BallotNav “origin story”: Why BallotNav? Who is our audience/user? How does it benefit the democratic process? 
    - Goal is to bring everything about BallotNav together in one deck to be reviewed by new team members and get them onboarded 
             efficiently. 
    - Current issues that may be incorporated into this issue:
              - Create Issues for Product Strategy Documents #403
              - Develop on boarding process for new team members #450 

**Time Permitted Items (can wait until regular weekly meeting):**

Demo of BallotNav is set. Ready to be presented to potential partners for evaluation and collaboration: 
- Create a clickable prototype for BallotNav #407- is this the same as the demo? Completed? Close issue?
- Create Product Journey Presentation #408- This should be a priority once a PM is comfortable with everything related to BallotNav. Maybe best for Karen if we are to move on this soon, as she has been with the project the longest.

Recruiting: 

- 2 Back End Engineers. Ideally would have experience updating features and functions in existing applications. Experienced engineers preferred. 
       - Need to post this on the Open Roles board for the next On Boarding meeting.
       - Draft language for posting.
- Data Science- will be needed in the near future but not quite yet.

**Comment by kcoronel** [comment]
02/11/22 Agenda for PM Pre-Onboarding 

### Roll Call
Karen
Stacey
Layne
Punit
Gayathri

#### Priority Items
Welcome to BallotNav and Roadmap Review: 
- Intro to the BallotNav project for new PMs
- Brief overview of Roadmap

**Review New Issue Approval list:**
- Issues pulled from Icebox and Prioritized Backlog to gain a sense of current work to be assigned to PMs. 

**Create New Issue Demo:**
- Create a new issue to create a Kickoff Deck for new team members.
    - Details on the BallotNav “origin story”: Why BallotNav? Who is our audience/user? How does it benefit the democratic process? 
    - Goal is to bring everything about BallotNav together in one deck to be reviewed by new team members and get them onboarded efficiently. 
    - Current issues that may be incorporated into this issue:
              - Create Issues for Product Strategy Documents #403 
              - Develop on boarding process for new team members #450 

**Time Permitted Items (can wait until regular weekly meeting):**
Review and Clean Up of the Kanban Board:
- Will spend time after the Pre-Onboarding meeting to clean up Kanban. 
- Need to complete this before creating new issues from Roadmap. 

Demo of BallotNav is set. Ready to be presented to potential partners for evaluation and collaboration: 
- Create a clickable prototype for BallotNav #407- is this the same as the demo? Completed? Close issue?
- Create Product Journey Presentation #408- This should be a priority once a PM is comfortable with everything related to BallotNav. Maybe best for Karen if we are to move on this soon, as she has been with the project the longest.
- 

Recruiting: 
- 2 Back End Engineers. Ideally would have experience updating features and functions in existing applications. Experienced engineers preferred. 
       - Need to post this on the Open Roles board for the next On Boarding meeting.
       - Draft language for posting.
- Data Science- will be needed in the near future but not quite yet.

**Comment by staceyrebekahscott** [comment]
Reviewed issues noted in agenda, moved back into Prioritized Backlog. Issue #403 will be broken into smaller issues. Issue #450 maybe incorporated into a Kick-off deck / onboarding issue TBD. 

New items were added to kanban, to be addressed before roadmap can be completed (roadmap issue moved to Backlog).
