### ISSUE TITLE
Validate BallotNav Product-Market Fit

### ISSUE THREAD

**Issue by layneam** [hackforla/ballotnav#454]
### Overview
Given the challenges inherent in harvesting and normalizing data from each election district, the BallotNav team has made the decision to pivot to an open-source model that local governments and/or community partners can use to display ballot drop locations to voters. This may require a different approach to meet the needs of the new target audience.

### Action Items
- [ ] Determine & recruit interview audience
- [ ] Conduct & synthesize user interviews
- [ ] Review opportunit(ies) with the BallotNav/HfLA team

**Comment by staceyrebekahscott** [comment]
This issue has expanded into this full project. We are starting with validating the idea of BallotNav itself in its current iteration, and will be organizations, rather than users, at this time to determine whether BallotNav is a viable solution to voting issues.
