### ISSUE TITLE
Updating Wiki Page for BallotNav

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/ballotnav#456]
### Overview
Welcome to BallotNav! wiki page needs to be updated. 

### Resources/Instructions
[Welcome to BallotNav!](https://github.com/hackforla/ballotnav/wiki/Welcome-to-BallotNav!)
[BallotNav demo video](https://drive.google.com/file/d/176QRO4pNVmGh7kecVOEH2F8sFftd35Eb/view?usp=sharing)

**Comment by yoursgayathri** [comment]
Created a [wiki page draft](https://docs.google.com/document/d/1bjVlgVfbzYSWi--ZJ1MdvqT3YIG8UP-H/edit).  @staceyrebekahscott  @kcoronel  @layneam  have reviewed and added comments. @yoursgayathri to make final updates to [Wiki Page](https://github.com/hackforla/ballotnav/wiki/Welcome-to-BallotNav!)

**Comment by staceyrebekahscott** [comment]
@yoursgayathri @kcoronel The Team Roster should be reorganized, as it looks confusing for new people to add their info. The active users are at the top, then there is a long list of inactive users. It is unclear what a new member should do. Maybe the Inactive should be on a separate sheet? Was there a reason it was organized in this way? (I add this comment in this issue as the Wiki is our intro to new members and everything it links to reflects a first impression.)

**Comment by kcoronel** [comment]
@staceyrebekahscott added columns to separate active and inactive users. How about stating this on the wiki page so folks know what to do 

Ex: Please fill out the roster with your name in the empty cell and list yourself as Active.

**Comment by yoursgayathri** [comment]
@kcoronel  made changes to separate active users and inactive users and updated wiki.

**Comment by staceyrebekahscott** [comment]
@yoursgayathri Not sure if you'd be interested in this, but there is an open issue in the Guides Tracker for creating a Wiki: [Create a Guide: Create a wiki for your project #36](https://github.com/hackforla/admin/issues/36). Since you updated ours you may want to reach out to the Guides team as they may value your thoughts on the guide creation.

**Comment by kcoronel** [comment]
@yoursgayathri can we please add this demo to our wiki as well: https://www.figma.com/proto/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=3719%3A13582&scaling=scale-down&page-id=3719%3A11979

**Comment by staceyrebekahscott** [comment]
@kcoronel @layneam I am closing this issue, as Gayathri is taking a break and I think the Wiki looks fine for now.
