### ISSUE TITLE
Review FoodOasis collaboration with Food Cycle LA

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/ballotnav#463]
### Overview
Review FoodOasis collaboration with Food Cycle LA and see if this could be a way that BallotNav can function. 

### Action Items
- [ ] Confirm contact details for Gigi
- [ ] reach out to schedule meeting
- [ ] develop agenda and questions to ask
- [ ] Meeting with Gigi
- [ ] Prepare notes and add document to Google Docs
- [ ] Share with team and gather feedback

### Resources/Instructions
Note from PM meeting on 02/19/22:
1 PM team member to reach out to Gigi from the Food Oasis to talk to set up time to meet with her and discuss some of the following: What are Food Oasis OKR's, what are they focused on this year, what are some user insights they've had as it relates to interface

Renting cloudbase BallotNav software to jurisdictions so we are taking care of security and data, and jurisdiction can embed it on their site using an iframe. Any government site can pre-search the BallotNav site and put it on their site on an iframe Ex: https://www.foodcyclela.org/find-food/

**Comment by staceyrebekahscott** [comment]
@kcoronel Is it Gigi Cobos that I should be reaching out to? Do you know her Slack name, or her email?

**Comment by kcoronel** [comment]
@staceyrebekahscott I am actually not sure, but I would go with Gigi Cobbs since she is in the PM CoP slack.

**Comment by staceyrebekahscott** [comment]
Moving this to Prioritized backlog, as issue #462 is my priority at this time. I believe our time is better spent figuring out details on our direct competitors rather than the project we were modeled after.

**Comment by staceyrebekahscott** [comment]
Added research label, as this may be an appropriate task for a beginner researcher.

**Comment by staceyrebekahscott** [comment]
- Due to revised thinking on this issue, moving to Market Fit project. 
- Revised thinking is related to issue #489 
- May reevaluate focus of this issue based on work done in issue #489 
- This may be a part of a review to see how other projects are approaching their long term sustainability planning for their projects

**Comment by staceyrebekahscott** [comment]
Closed issue as it pertains to an earlier iteration of BallotNav. New direction is being mapped out in issue #490 and it is not necessary to align our strategy with Food Oasis.
