### ISSUE TITLE
feature: data loader script

### ISSUE THREAD

**Issue by jafow** [hackforla/ballotnav#47]
### Overview
We need to be able to take data from airtable or raw csv and import it into a database.
This should be able to be run regularly with minimal manual intervention, even automated!

### acceptance criteria
1. we can take 1 or more correctly formatted files from air table and load them into a format the application can return
2. the script can be run often by more than one person and with minimal manual intervention
3. the script can be run against and tested against a local running instance before running on the live db

### Action Items
- [ ] write a script that can, 1 or more csv files and move them into a format the application understands

## approach 1

Write a python or SQL script that reads each line of the csv and executes on the db. 
Python's `psycopg2` library is very good for this. 
```python
# psuedo code warning

connection = psycopg2.connection("postgres://ballotnav:secretpassword123@my-database-name.balotnav.org:5432/main")

with open("import-data-from-airtable.csv") as f:
     reader = csv.DictReader(r)
     with connection.cursor() as cursor:
         for line in reader:
             cursor.execut("insert into dropoff_table values {**line}")

```

This should be straightforward for a singel table, but gets trickier as the data relationships expand. 
          
 
### approach 2
write JSON API calls to the application

e.g. 

```python

for line in csv_file:
   response = requests.post("https://ballotnav.org/api/locations", {"data": line})
   if response not in requests.ok:
       print("we got an error on this line: ", line)
   else:
       print("created this : ", line)
```

This way seems more maintainable & automatable but has the dependency on us writing the app!

**Comment by Henrymarks1** [comment]
I'll take a shot at this issue @jafow

**Comment by ExperimentsInHonesty** [comment]
@jafow @Henrymarks1 Since the requirements for this have changed from many times import to a one time import, please update with acknowledgment of change and plan for importing into Postgres.  Also Product (@Arjayellis ) will have all of the initial state data to import into the db by the end of day 9/20.  All future updates will be made through the interface that we are building that will work directly with the Postgres db.

**Comment by kcoronel** [comment]
Hi @aNullValue @jmensch1 @adamkendis @jafow can you please confirm that Bonnie's comment has been finalized? Thank you

**Comment by aNullValue** [comment]
This ticket is no longer relevant. All of the management is now being done in-app.
