### ISSUE TITLE
Competitive Analysis for BallotNav 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#478]
### Overview
As part of our efforts to make BallotNav a competitive product, we need to analyze the existing market's products as well as the features that make them unique. 

### Action Items
- [x] Review other HackforLA projects for the best competitive analysis format to use and add links to this issue 
- [x] Bring established format to the team 
- [x] Outline the process and place in this issue 
- [x] Anyone who analysis a competitor will need to write any questions, blockers, and updates to this issue 
- [x] Begin competitive analysis 
- [x] Summarize results (format TBD) 

### Resources/Instructions
[Competitive or Comparative Analysis Template](https://docs.google.com/spreadsheets/d/1B9MME1LUqGXZvX5MsTWlGFJ6ETvHy4Eu3SFKg4d2iBA/edit?usp=sharing)

**Comment by layneam** [comment]
@kcoronel : I started a document [here](https://docs.google.com/spreadsheets/d/16oLO--cEOMx75jg-zWfZTj1oRTailr6jFLrogH554pQ/edit?usp=sharing) with some notes on toolsets available from a couple orgs. I'll show that to the team in our regular meeting and see if I should press on with it.

**Comment by staceyrebekahscott** [comment]
@layneam @kcoronel @yoursgayathri I think we should be able to close or archive this issue, as a large part of what we are addressing  in the Market Fit Research project is competitive analysis. 

What is the criteria that was used to justify archiving the issues from the icebox vs noting and marking the issue as closed and moving to the Done column?

**Comment by staceyrebekahscott** [comment]
- Moved to Market Fit Research project as the scope of this issue is also being addressed in the Market Fit project.

**Comment by staceyrebekahscott** [comment]
Google Sheet: [2022 Indirect and Direct Competitors | BallotNav Research Repository](https://docs.google.com/spreadsheets/d/11PYjjs8EkUgRhQ55crn9Eu6IgPx9qjPb0GWx2Zt_bUM/edit#gid=0)

Google Slide Deck [Voting Organization Research Slide Deck](https://docs.google.com/presentation/d/1sfz3gSzqUbMzamy1cWUXHMNZdGF8C6fCGZCazKSDH7o/edit#slide=id.g127b51c867a_3_0)

Above are links to the competitive analysis for BallotNav conducted in April/May 2022. I am closing this issue, as this is the most recent analysis conducted for BallotNav.
