### ISSUE TITLE
Voting Organization Research: Potential Partnership Organizations

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/ballotnav#481]
### Overview
Develop a methodology on how to understand the purpose of voting advocacy organizations. These organizations may serve as partners for us if/when we are ready to market BallotNav. 

Questions to start with:
- What their goals as an organization are
- What actions do they take to engage voters
- What pain points do they identify as barriers to voting

### Action Items

- Decide what is the best way to collect and display data (spreadsheet, slide deck)
- Develop a process for how to analyze the website (possibility this can be used to build a guide for HfLA)
- Gather as much data as possible from website, news articles, interviews

### Resources/Instructions
UX team to develop process for how to conduct research and organize data.

**Comment by staceyrebekahscott** [comment]
Moved to prioritized backlog. To be reviewed as part of issue #449

**Comment by staceyrebekahscott** [comment]
This issue will be the basis of the new project we will develop in order to determine the future of BallotNav. 

Next steps are to organize a place in the Google Drive where we can start brainstorming on what this new project will look like. 

- [ ] Create Folder in Google Drive for new project (name TBD)
- [ ] Start document for brainstorming ideas for next steps (organizations to research, research methods, processes to employ, etc)
- [ ] Schedule UX meeting for next Mon or Tues to organize brainstorm ideas and form an outline of next steps 
- [ ] Present outline at Team Meeting next Tuesday.

**Comment by staceyrebekahscott** [comment]
There are 2 items that pertain to Potential Partners: 

Google Doc (created from recent brainstorming doc): [Potential partnership organizations](https://docs.google.com/document/d/1rEvB2_KXIja_oWBVZhXA9Nt0oI3hmn9DvfQNU0VffKA/edit)
Google Spreadsheet (originally created in 02/2021 and last updated 04/2021): [Ballot Nav Potential Partners](https://docs.google.com/spreadsheets/d/1G42xVXKWNxcy2oOi2uBCtfIKyE4yUqp703vCKbE3I8Y/edit#gid=1595301577)

We should consolidate this information into the spreadsheet, and update the "notes" column, adding the new description from the newer Doc.

**Comment by jonlam27** [comment]
Drafted up some potential research questions to best analyze the websites of organizations we may want to partner with, which were included alongside Zuri's own list of questions. Started doing some research on the organizations in [Potential partnership organizations docs](https://docs.google.com/document/d/1rEvB2_KXIja_oWBVZhXA9Nt0oI3hmn9DvfQNU0VffKA/edit) and gathered info in the [Research Repo](https://docs.google.com/spreadsheets/d/11PYjjs8EkUgRhQ55crn9Eu6IgPx9qjPb0GWx2Zt_bUM/edit#gid=13952782) that Zuri created.

**Comment by staceyrebekahscott** [comment]
@jonlam27 Please add any updates for work done in the past week ahead of the team meeting this evening.

**Comment by staceyrebekahscott** [comment]
Posted note on # ballotnav-design channel for collaboration assistance on the competitive analysis and partnership spreadsheet.

**Comment by kaerii** [comment]
@jonlam27 Happy to help out with the spreadsheet!

**Comment by kaerii** [comment]
I added a "Partnerships and affiliations" and "Board of directors" row to the spreadsheet since many of the organizations have a dedicated page to this. I thought that having these for reference would be useful for creating our own board of directors and choosing organizational partners.

**Comment by jonlam27** [comment]
Neat, thanks @kaerii!

**Comment by staceyrebekahscott** [comment]
@jonlam27 I see progress made on the spreadsheet and collaboration with Carrie. This looks great! 

How close are you to calling the spreadsheet completed? Will you be ready to present it to the team by this week's meeting?

**Comment by staceyrebekahscott** [comment]
@jonlam27 Will you be prepared to make a short presentation on the partnerships spreadsheet at tomorrow's team meeting? 

I see progress and collaboration on the spreadsheet, and it looks great. Nice job on this!

**Comment by jonlam27** [comment]
Yup shouldn't be an issue @staceyrebekahscott  - Zuri and I will present our findings in a short pres tonight

**Comment by jonlam27** [comment]
[Link to the slide deck for reference](https://docs.google.com/presentation/d/1sfz3gSzqUbMzamy1cWUXHMNZdGF8C6fCGZCazKSDH7o/edit?usp=sharing)

Thanks again to @zuriisawesome, @kaerii, and @seyounglee2001 for all your help!

**Comment by staceyrebekahscott** [comment]
@jonlam27 Great Job on the slide deck. It is well organized and you and Zuri seemed to work well together. 

Is there anything that needs to be finished up on this? If not, I'd like to mark this closed and done!

**Comment by staceyrebekahscott** [comment]
@jonlam27 Checking in on my last comment, is there anything else that needs to be finished up on this issue?

**Comment by jonlam27** [comment]
yup, all good to close, thanks for checking @staceyrebekahscott !

**Comment by staceyrebekahscott** [comment]
Reopened issue #487 as the slide deck created needs to follow the formatting detailed in the BallotNav Communications Guide.
