### ISSUE TITLE
Backend Knowledge Transfer for Ballot Nav - Touch base with Drew

### ISSUE THREAD

**Issue by yoursgayathri** [hackforla/ballotnav#482]
### Overview
Meet with Drew to understand the current product and discuss the changes to be made to it in order to build our MVP.

### Action Items

- [ ] Get access to the admin I/f for @yoursgayathri @kcoronel @staceyrebekahscott @layneam 
- [ ] Document for Data model/Architecture
- [ ] Another Meeting with Drew to further discuss the MVP

### Resources/Instructions

@yoursgayathri  had an initial conversation with Drew  and he walked her through the high level architecture of the BallotNav software.  The current model is a open source model where BallotNav hosts a copy of the software and the data. The database is uploaded and maintained by the BallotNav volunteers. The future model had already been discussed in the past to be a per-jurisdiction federated solution, where each jurisdiction can maintain their own data. This would entail us providing automated data import for adopters.

[BallotNav High Level Architecture](https://docs.google.com/presentation/d/1cjL8cAzC7XRGkpVML2hUtA_VpFSQcr0X/edit#slide=id.p1)

**Comment by yoursgayathri** [comment]
@yoursgayathri  @layneam @kcoronel @staceyrebekahscott  will have a meeting with drew to discuss the following Agenda items. 

- [ ] How much work would be involved to develop the data uploading interface?
- [ ] How much effort to redesign backend to accommodate multi- jurisdiction.
- [ ] How much work will it be to convert to a service model rather than open source model.
- [ ] What are the costs that may be implicated with service model?
- [ ] Effort to accommodate multiple languages

Drew said that he is available most days after 6PM PST. We can setup a common time during our next PM meeting.

**Comment by kcoronel** [comment]
@layneam @kcoronel to review to make sure everything was captured

**Comment by staceyrebekahscott** [comment]
@yoursgayathri @kcoronel @layneam Has there been any progress in getting the backend access? I believe Jake(?)  needed to be contacted, but last this was discussed was a few weeks ago. What is the current status on this?

**Comment by layneam** [comment]
@jmensch1 @aNullValue Hi fellas, we were just talking about this today in our team meeting. It would be really helpful to have the backend access open to the rest of the team and documented so people in the future can get in. Jake are you able to lend us a hand please?

**Comment by jmensch1** [comment]
hey! It's been a minute but I can probably help get the backend running on someone's computer. let me know what day/time would be good.

**Comment by staceyrebekahscott** [comment]
We need to research what is the proper way to document website access, where the code should be stored in GitHub, and where the website should be hosted, as the post above implies that the backend would need to run on someone's computer (why not on HfLA supported storage like AWS?).

**Comment by staceyrebekahscott** [comment]
@jmensch1 Hi Jake, is the backend currently running on your computer? And if so, can you expand on why the site was set up to run this way?

**Comment by staceyrebekahscott** [comment]
[Layne (AEST)](https://app.slack.com/team/U032H8FJX6U)
 [Today at 4:09 PM](https://hackforla.slack.com/archives/C032MFWFNE5/p1655248189321319)
 It looks like the code is on GitHub already.
hi Layne, yeah all the code is on github here: https://github.com/hackforla/ballotnav. you might need to get access from Bonnie. There are README docs in there that explain how to set up the various pieces of the app
1 reply


[Layne (AEST)](https://app.slack.com/team/U032H8FJX6U)
  [1 hour ago](https://hackforla.slack.com/archives/C032MFWFNE5/p1655248256571449?thread_ts=1655248189.321319&cid=C032MFWFNE5)
i.e. https://github.com/hackforla/ballotnav/tree/master/backend

**Comment by aNullValue** [comment]
Yes, the code has been in the github repo since day 1. There's no access necessary; it's an open repository and anyone in the world can see it. 

The site wasn't so much set up to run on an individual's laptop so much as it's not currently running in any production environment, so on some individual's computer is the logical place where it could be run for demonstration purposes.

**Comment by jmensch1** [comment]
yeah it used to run on AWS like other HFLA projects, i’m not what the status of that infrastructure is though.

**Comment by staceyrebekahscott** [comment]
@layneam @kcoronel As per the conversation at the last team meeting, we do not need to do anything with the website at this time. Closing this issue and removing assignments.
