### ISSUE TITLE
Project Documents for Market Fit Research

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/ballotnav#483]
### Overview
Develop a project charter, SMART Goals, Scope and Timeline for market fit research project.

### Action Items
- [x] Create Project Documents board in Miro
- [x] Review with team 

Project Charter Outline:
- Purpose
- Scope
- Success Criteria (SMART Goals)
- Team
- Stakeholders
- Users
- Resources
- Constraints
- Risks
- Timeline

Miro Board
- [x] Guide for project charter (Search in the Guides tracker) *Did not find a guide for a project plan or charter

Link to Miro: [Market Fit Research Project Documents](https://miro.com/app/board/uXjVO9_TkJE=/)
- Charter
- SMART Goals
- Timeline

**Comment by staceyrebekahscott** [comment]
Notes from brainstorming Google doc: 

Communication Plan ideas (as part of the project plan):

- Process for creating, updating and closing out issues
- How do we collaborate and share feedback
- Expectations of progress, ex: what work can be done in a given time, availability to do the work, coordination of schedule, what can we commit to the project and each other
- Meetings- how should they be conducted and structured, what do we need to do as a group, as individuals, as small groups

**Comment by staceyrebekahscott** [comment]
HfLA Guides related to PM or project planning:

[Prioritizing features for your project # 155](https://github.com/hackforla/product-management/issues/155)
[How to assign and work on an issue  # 227](https://github.com/hackforla/product-management/issues/227)
[PM Terminology # 314](https://github.com/hackforla/product-management/issues/314)
[Story points for your project # 18](https://github.com/hackforla/ops/issues/18)
[Terms and conditions for your project # 114](https://github.com/hackforla/product-management/issues/114)

**Comment by staceyrebekahscott** [comment]
@kcoronel @layneam @yoursgayathri The links below are summaries of the Market Fit and Board of Advisors projects I'd like to send to Bonnie. Please review and let me know if you have any feedback. 

[Project Update: Market Fit Research](https://docs.google.com/document/d/1-VYlyJFlnfgMMUrTIR15bSiskiGJK6NxR7R_Cc1fCFA/edit)

[Summary: Current Status of Board of Advisors project](https://docs.google.com/document/d/1zlN4f7uVzjleZXva-0S2mME61dAggFe6OmdaOytCda0/edit)

**Comment by staceyrebekahscott** [comment]
I am asking the UX team for feedback on Miro as a communication tool for the project documents. I am learning the tool and evaluating if it is working, or if I should use a different process. 
- Made updates as of 05/05/22, asked Jon to review.

**Comment by staceyrebekahscott** [comment]
[Qualifying Survey June 2022](https://docs.google.com/forms/d/1GADkFOXhVtGV-Dndy5-pnEMMBD74ZoOWkGhPTJ_axVI/edit)

**Comment by kcoronel** [comment]
Closing this issue because it looks like all tasks have been completed.
