### ISSUE TITLE
Academic Literature Published Work: Current state of voting via ballot drop off

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/ballotnav#486]
### Overview
A collection of relevant voting published work relating to voting via ballot drop off boxes. This issue is to serve as a hub of articles related to the topic, and an analysis and conclusion statement will be drafted based on the findings. 

The team will decide when enough work has been collected to develop a conclusion. 

Google Doc: [Academic Literature Published Work](https://docs.google.com/document/d/1vyUX0H0hkVkJtcWXTvH0BTza5FixYoRL7Aog8NMh3sI/edit#)

Completed Slide Deck: [The State of Ballot Drop Box Voting in 2022 ](https://docs.google.com/presentation/d/1u6ZYntaK82J4pX3x36iH0zc1kz4KDtFEhbRfSUKY0l4/edit#slide=id.p)

**Comment by staceyrebekahscott** [comment]
Comment by Carrie from Slack BallotNav-Design channel: 
"I also looked a little bit into the future of ballot drop off box use. I think, since we are doing this foundational stage of research to gauge whether there will still be a need for the product, an important area to understand would be if ballot drop off boxes will still be widely used post-pandemic, which states have drop off boxes/are making them permanent, which states are opposed to drop off boxes or are actively enacting legislation banning drop off boxes."

@kaerii I think this is a great idea. Please continue to research this and add any articles and summaries to the doc in Google called [Academic Literature Published Work](https://docs.google.com/document/d/1vyUX0H0hkVkJtcWXTvH0BTza5FixYoRL7Aog8NMh3sI/edit#)

**Comment by staceyrebekahscott** [comment]
@Lihuizhang53 @kaerii Please feel free to reorganize the Google doc for this issue as you see fit. We should establish a format for how the research is presented. It appears as though the format established in the doc is:

- Outline of article
- Citations

I think links to the articles should also be added. Should we continue in this format or do you have any other ideas?

**Comment by staceyrebekahscott** [comment]
Message to Carrie and Lihui re: this issue was posted in the Slack BallotNav-Design channel.

**Comment by staceyrebekahscott** [comment]
@kcoronel @layneam @yoursgayathri I'd like your help with finding any existing guides within HfLA that pertain to organizing and presenting findings from academic research articles. Or if you have any experience or references that you have used in other contexts, either from conducting research, or a presentation that you found particularly helpful.

**Comment by kaerii** [comment]
It would be great to figure out a better way to organize the research. If there's any existing templates, that would be great, or Lihui and I could connect to figure something out. One problem with including links is that a lot of academic articles are behind paywalls and the links aren't very useful. I could download the articles and put them in another Google drive folder though.

**Comment by staceyrebekahscott** [comment]
@kaerii I created a sub folder within the Market Fit Research folder for downloaded articles: [Academic Literature Published Work Folder](https://drive.google.com/drive/folders/1ZgJGD5T4yxiewJOO3o5-oYkOS9UBwXAF). I moved the existing doc (with the same title) into the folder. 

This was a good suggestion, Thank You.

**Comment by kaerii** [comment]
I've finished a literature review focusing on drop off box use and am working on making a findings report/slide deck for the upcoming week. The google doc of the literature review and PDFs of articles has been uploaded to the drive.

**Comment by staceyrebekahscott** [comment]
@kaerii I just reviewed the slide deck and it looks great. How close are you to calling it finished? Will it be ready for you to present to the team at this week's team meeting?

**Comment by kaerii** [comment]
@staceyrebekahscott yes, I'll be able to present it at the team meeting this week

**Comment by staceyrebekahscott** [comment]
@kaerii Great. Please plan on spending about 5-10 min presenting your findings via the slide deck and answering any questions from the team. Great work!

**Comment by staceyrebekahscott** [comment]
@kaerii Re: the question raised by Drew during the team meeting: for states that are limiting drop boxes, what exactly are the restrictions? (ex: in Ohio, they are limiting to 1 per county and if there is a ballot from another county, they are not obligated to forward it through). 

I am wondering if it is worth finding this out for 1 or 2 states and adding it to the slide that discusses voter attitudes (slide 7). It is not critical information, but it might just complete the statement regarding drop boxes becoming a partisan issue. How long would it take for you to research this and add it to the slide? What are your thoughts on how this adds value? 

If it will take too long or you think it may not add anything significant, then I don't think you should bother. 

Other than that, it appears as though the only thing to finish up here is the references slide. Is this correct? And what would be your time estimate for getting that completed?

**Comment by kaerii** [comment]
@staceyrebekahscott I can find out some information about restrictions; for 1-2 states it should be quick. The references slide is done; it just links to the full reference google doc.

**Comment by kaerii** [comment]
I added a slide on restrictions and changed the wording of the references slide. The deck should be complete now.

**Comment by staceyrebekahscott** [comment]
@kaerii @Lihuizhang53 Thank you for your effort and hard work on this issue. I am going to close it and move it to the Done column. And we will get you assigned to another issue this week.

**Comment by staceyrebekahscott** [comment]
- Reviewed Carrie's updated slide on voting restrictions
- Sent slide deck link to PM's via Slack
- Updated Overview section to include link to completed slide deck
- Updated Carrie and Lihui on status of issue
- Added notes, closed and moved to Done

**Comment by staceyrebekahscott** [comment]
@kaerii I have reopened this issue and assigned it back to you. It was brought to my attention that all slide decks created for BallotNav, for internal and external use, must follow the formatting detailed in the BallotNav Communications Guide. Please see the links below and update this slide deck accordingly. Thank You!

[BallotNav Communications Guide for Document Creation [INTERNAL]](https://docs.google.com/presentation/d/1240MJDl2PA6NcchLwVdGvweI-dC_E4u4-V8jmHNz_LI/edit#slide=id.g8078b36bb8_0_35)

[BallotNav Presentation Template](https://docs.google.com/presentation/d/1FEXrgKYBbM7z93jfQxw6buaz5NhlfSonI6DXqHlrRhE/edit#slide=id.gee3d443e9e_0_79)

**Comment by kaerii** [comment]
@staceyrebekahscott I've updated all my documents and slides.

**Comment by staceyrebekahscott** [comment]
@kaerii Thank you for taking care of this so quickly. The docs and slide deck look great.  Issue is closed, again! :)
