### ISSUE TITLE
Competitive Analysis: Direct and Indirect Competitors

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/ballotnav#487]
### Overview
A list of competitors that have a website or app that functions in a similar way to BallotNav. 

### Resources/Instructions
Google Folder: [Competitive Analysis](https://drive.google.com/drive/folders/1yRPgBBBaDDTRdo7vhqDfmjxQ_dHnzaqP)

- [x] Figure out how to organize the data, combining old and new research.

**Comment by staceyrebekahscott** [comment]
@zuriisawesome Thanks for taking this issue. I'd like to know what thoughts you have on how to best organize the data. If you could have a few suggestions by tonight's team meeting that would be great.

**Comment by staceyrebekahscott** [comment]
@zuriisawesome Please add any updates to this issue here ahead of the team meeting tonight.

**Comment by zuriisawesome** [comment]
I've created a spreadsheet to organize both past research and the current market fit research, located [here](https://docs.google.com/spreadsheets/d/11PYjjs8EkUgRhQ55crn9Eu6IgPx9qjPb0GWx2Zt_bUM/edit). Each tab is labeled, with 1.0 representing older research and 2.0 representing the current project. I've come up with the questions in collaboration with @jonlam27, who is currently filling out the Partnerships tab. I've begun filling out the Direct and Indirect competitors tab

**Comment by staceyrebekahscott** [comment]
Posted note on # ballotnav-design channel for collaboration assistance on the competitive analysis and partnership spreadsheet.

**Comment by kaerii** [comment]
@zuriisawesome Happy to help with filling out some of the spreadsheet!

**Comment by staceyrebekahscott** [comment]
@zuriisawesome I see progress on the spreadsheet and collaboration with Carrie and Jon. This is awesome! 

How close are you to having this spreadsheet completed? Will you be ready to present it to the team at this week's team meeting?

**Comment by zuriisawesome** [comment]
Hi Stacey! the progress looks great – many thanks to Carrie for helping out. I think @kcoronel mentioned wanting to add info on 2 orgs – my section still has one missing while Jon's might have 1-2. I think it may be better to present at next week's meeting

**Comment by staceyrebekahscott** [comment]
@zuriisawesome The spreadsheet looks great, and I see updates from other team members. So nice to see this collaboration. 

Will you be prepared to make a short presentation at tomorrow's team meeting?

**Comment by staceyrebekahscott** [comment]
@zuriisawesome Again, Great Job! The slide deck is really well organized, easy to navigate and you and Jon seemed to work really well together. 

Is there anything else regarding this issue that you needed to finish up,? If not, I'd like to close it and mark it done!

**Comment by staceyrebekahscott** [comment]
@zuriisawesome Checking in on my previous comment, is there anything else on this issue that needs finishing up?

**Comment by staceyrebekahscott** [comment]
@zuriisawesome @jonlam27 I am reopening this issue and assigning you both, as you collaborated on the slide deck. It has been brought to my attention that all slide decks, for internal and external use, must follow the formatting detailed in the BallotNav Communications Guide. Please see the links below and update the slide deck accordingly. Thank You.

[BallotNav Communications Guide for Document Creation [INTERNAL]](https://docs.google.com/presentation/d/1240MJDl2PA6NcchLwVdGvweI-dC_E4u4-V8jmHNz_LI/edit#slide=id.g8078b36bb8_0_35)

[BallotNav Presentation Template](https://docs.google.com/presentation/d/1FEXrgKYBbM7z93jfQxw6buaz5NhlfSonI6DXqHlrRhE/edit#slide=id.gee3d443e9e_0_79)

**Comment by jonlam27** [comment]
Hey @staceyrebekahscott sounds good, I'll go ahead and change the slide deck to match the formatting in the guide!

As we now have more researchers, do we want to review the guide a bit more as there wasn't much of that when I first worked on it and some parts within the guide are still incomplete.

**Comment by staceyrebekahscott** [comment]
@jonlam27 Thanks Jon. I'll remove @zuriisawesome if you're cool with updating the slide deck. And I'll send a separate message from the guide issue in the BallotNav 2.0 board.

**Comment by jonlam27** [comment]
That works - the [slide deck](https://docs.google.com/presentation/d/1sfz3gSzqUbMzamy1cWUXHMNZdGF8C6fCGZCazKSDH7o/edit#slide=id.g127a3020332_0_60) has been updated btw 👍

**Comment by staceyrebekahscott** [comment]
Reviewed updated slide deck. Moved to Done column.
