### ISSUE TITLE
Document product-market fit approach

### ISSUE THREAD

**Issue by layneam** [hackforla/ballotnav#490]
In conversation with the product management team ~the week of 16 May, a more detailed document is needed on the approach proposed to take Ballot Nav 2.0 forward. Questions include:
What is the proposed project approach and why?
What is the proposed next step?
What process should we follow to complete this step?

**Comment by layneam** [comment]
Approach presentation delivered to the Ballot Nav team on 24 May 2022 PST (25 May AEST): https://docs.google.com/presentation/d/1zJIJ9OPeBeTKnJcjVXeUnuKmN4I-TbCqnuduHpnZ2r0

**Comment by staceyrebekahscott** [comment]
Notes and action items from the team meeting on 05/24/22: 

- Using our own networks to find customers to interview: Drew's connection with Code for America, Karen's networks with political groups
- Need to put together who we are interested in talking to
- Templates & Script: for consistency. Starter questions, then can elaborate during the interviews
- Group voting orgs by similarities, work on personas- Carrie & Zuri
- Template for Outreach- Karen
- Starter questions- Layne
- Need to think about what our 3 big challenges we are most concerned with. This will become more clear once we see the personas. 
- Qualifying surveys? (this was not assigned).

**Comment by layneam** [comment]
Starter questions (Draft for discussion with the team): https://docs.google.com/document/d/1fgngzGPxVUrLqKr5sYp4Uj5u1aPLeE6QeHz7xwEFL64/edit?usp=sharing

@kcoronel once our personas are ready are you happy to write the qualifying survey? Or would the UX team prefer to do it? cc: @kaerii & @zuriisawesome

**Comment by staceyrebekahscott** [comment]
@kaerii @kcoronel @layneam @staceyrebekahscott Please list availability for next week for Layne to add to Calendly.

**Comment by layneam** [comment]
I'm avail:

- Saturday 11 June 3PM-7PM PST
- Sunday 12 June 3PM-7PM PST
- Monday 13 June 3PM-6PM PST
- Tuesday 14 June 3PM-6PM PST
- Wednesday 15 June 3PM-6PM PST
- Thursday 16 June 3PM-6PM PST
- Friday 17 June 3PM-6PM PST

**Comment by staceyrebekahscott** [comment]
Issue #492 created and assigned to Layne

**Comment by kaerii** [comment]
I'm available 
S 6/11 1-4pm EST
Sun 6/12 4-7pm EST
M 6/13 5-7pm EST
T 6/14 1-4pm EST
W 6/15 1-4pm EST
Th 6/16 4-7pm EST
F 6/17 1-4pm EST

**Comment by kcoronel** [comment]
I'm available 
M 6/13 - 5-7pm EST
T 6/14 7-9pm EST 
Th 6/16 11-3pm EST 
F 6/17 2-6pm EST

**Comment by staceyrebekahscott** [comment]
- Will continue adding notes on documentation and process to #483, all other issues related to this phase of the project will also be linked to #483 

@layneam Removing you from this issue and closing.
