### ISSUE TITLE
Qualifying survey for potential interviewees (Google Forms)

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/ballotnav#493]
### Overview
We will create a prequalifying survey for potential interviewees who respond to the Reddit post using Google Forms. Form will feed into info a Sheet where we can then add the data we collect from the interviews.

### Action Items
- [x] Create survey in Google Forms 
Add survey to Reddit post (removing this as a requirement, as we were unable to post on Reddit as originally planned.)

**Comment by staceyrebekahscott** [comment]
Notes from team meeting on 06/07/22:

Google Forms fields:

- Name
- Email 
- Phone Number 
  - (Specify preferred contact method)
- Are you a volunteer or employee of a nationally based organization that mobilizes voters as its core mission? 
- Is your role at this organization paid or unpaid? 
- How would you describe your primary role in this organization?
  - Canvassing/ Voter Outreach
  - Policy/Research
  - Volunteer organizing/ Strategy
  - Management
  - Other (Please Specify)

**Comment by layneam** [comment]
Google Form is in Ballot Nav Shared Drive > Market Fit Research > Customer Development ([Link](https://drive.google.com/drive/folders/1unh54flAXwspRLh3sv0rYMkhJCpn5_65?usp=sharing))
Form: https://docs.google.com/forms/d/1GADkFOXhVtGV-Dndy5-pnEMMBD74ZoOWkGhPTJ_axVI/edit
Sheet: https://docs.google.com/spreadsheets/d/1iBwCE-jOt_KH6EYiGAEIad4ufOfvo-ynnJk_MaiXXPI/edit

**Comment by staceyrebekahscott** [comment]
- Added link to survey to issue #483 
- Use of the survey depends on our outreach method

**Comment by staceyrebekahscott** [comment]
@layneam Removed your assignment and closed issue, added link for survey to #483
