### ISSUE TITLE
Onboard UX Researcher: Brittany Anjou

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/ballotnav#499]
### Overview
Onboarding of Brittany Anjou to the BallotNav UX Team.

#### Onboard
- [x] Slack channel membership
  - [x] #ballotnav
  - [x] #ballotnav-design
- [x] Add to Google calendar invites
   - [x] Tuesday 6PM PST - All-team meeting
- [x] Tag PM to request for you to team page on Wiki
- [x] Google Drive
   - [x] Add to drive as Contributor 
- [x] Request roster from PM team 
  - [x] Team member adds themselves
  - [x] Check for 2FA and note in roster
- [x] GitHub
     - [x] Add to team write team
     - [x] Add to read vault
- [x] 1password 
     - [x] invitation
     - [ ] acceptance
     - [ ] add to vaults

**Comment by staceyrebekahscott** [comment]
@kcoronel Keep an eye out for Brittany's name on roster to get her repo access, etc.

**Comment by staceyrebekahscott** [comment]
Sent Brittany a message letting her know that Karen should be reaching out to her shortly.

**Comment by uxmusic** [comment]
Thank you @kcoronel  and @staceyrebekahscott for assisting in my onboarding! Looking forward -
