### ISSUE TITLE
Create Readme for website

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#5]
### Overview
 Update Readme so that people thinking about joining our project know how to contribute.

### Dependency 
Adding Project Card to hfa website: https://github.com/hackforla/website/issues/703

### Action Items
- [x] Review the readme resource and figure out what we can include in ours. Also look at the one for civic opportunity as an example
 - [x] Update our readme
- [x] Add link to project page on Hack for LA website, hackforla.org/projects/ballotnav (link will be up when page is finished when project card get's added to website #1 )
- [x] Add details about how people can get involved in the project (write a narrative description of the things people need to do with a bulleted list and link to the state project board) 

### Resources/Instructions
**Other readme's**
[Hack for LA's default](https://github.com/hackforla/.github)
[civic opportunity](https://github.com/hackforla/civic-opportunity)
[hackforla.org website](https://github.com/hackforla/website)

**our readme**
[BallotNav readme](https://github.com/hackforla/ballotnav)

**Comment by ExperimentsInHonesty** [comment]
Before the How to contrib section put another header that says 

More information about the project
put link to : 
https://docs.google.com/document/d/15tMTwUnPnfAeN1C4KP4mvGWaiz3IfkktTY4drKFa8eo/edit?usp=sharing
https://docs.google.com/document/d/1gWtxL74G2pGphoUKAnbul4UR93GfItuPzJKJC8_3up0/edit?usp=sharing

Change the #1 in contributing to be read the project context and more information about the project

**Comment by myastark** [comment]
Done

**Comment by ExperimentsInHonesty** [comment]
Moving to the questions column to wait for website team to add project card to website, so that we can link to it under the first paragraph with the words "Hack for LA BallotNav project page"
