### ISSUE TITLE
script: query mapbox for geocodes

### ISSUE THREAD

**Issue by jafow** [hackforla/ballotnav#58]
## Overview
We currently do not have any latitude or longitude data for any ballot dropoff location address, but the client requires these to render locations on the map. 

## Action Items
- write a script that reads a CSV file exported from air table and looks up the lat & lon for each address and saves the output

## Resources/Instructions
- get the mapbox api key from 1password
- familiarize yourself with their geocode api: https://docs.mapbox.com/api/search/#geocoding
- get the latest export from airtable as a csv

## requirements
- the script should be automatable -- e.g. minimum of manual intervention required, ideally a file input and output
- the script should log any failures and continue to fetch any geocode data even if one call fails (robust!)

## further considerations
- the input data will likely change a lot--new columns may be added, old ones removed so consider how much your program relies upon the current structure of the input and make it robust to change. 

- separate the input transformation from the output/saving code; it's likely that we will want to change the output from writing to a file to sending HTTP requests to the ballotnav backend. Consider making this part of the program swappable

**Comment by theswerd** [comment]
Done in pull request #62 by @Henrymarks1
