### ISSUE TITLE
Exceptions to Counties Table

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/ballotnav#68]
### Overview
We need an exception table of places that don't use the county as their election administration jurisdictions (EAJ) so that the lines in the map match the area.

### Dependency
 - [ ] Making sure the census data is applicable for voting

### Action Items
- [ ] Data Science
   - [ ] Identify the relevant fields needed
   - [ ] Create a table in called EAJ table Airtable with fields
   - [ ] Send to development 
Development
  - [ ] design conditional rendering of shape of the EAJ's based on EAJ Airtable to appear on the site

### Resources/Instructions
https://en.wikipedia.org/wiki/County_(United_States)#County_equivalents

**Comment by kcoronel** [comment]
@nickelworks anything on Census stuff? Thanks!

**Comment by aNullValue** [comment]
I've spent several hours working on determining exceptions to the "elections are administered by counties" rule. I've put my finding thus far in this Google Sheet, in the BallotNav Drive: [States with Jurisdiction Type Information](https://docs.google.com/spreadsheets/d/1vlnhPJAG5XwY5ismtQMiNvEoPKBMW0a_q7SaYTliH7s/edit?usp=sharing).

While I _anticipate_ that the rest of the states will be exclusively "County" (indicated as CB County/Equiv = Y), we need to verify that. And for all of the states that are not CB County/Equiv, we need to come up with an appropriate jurisdictional boundaries shape file.

Determining whether the state using "county" or something else is usually as easy as finding the state's election authority and reviewing their absentee ballot process, to see how you request or return your ballot. But finding the correct shape file for each jurisdiction may be very substantially more difficult.
