### ISSUE TITLE
Export Location Schema for Desigers

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/ballotnav#70]
### Overview
We need to provide the location schema for the designers to make sure they have all the info that is going to need to be on the location page. 

### Action Items
- [x] Export schema from locations table pasting in the comments below and annotating what they can ignore.

### Resources/Instructions
[Airtable](https://airtable.com/tbl7iu5KqFh1PwSmL/viwaFu9xo9izzsvPi?blocks=hide)

**Comment by ExperimentsInHonesty** [comment]
@IrinaRost @fedelandini This will be discussed at the Data Science meeting on Thursday night at 8pm and at that point we should a firmer idea of what the schema will be.

**Comment by aNullValue** [comment]
I'm providing example JSON data structure in slack: #ballotnav-backend periodically, and it's still subject to significant revision as the backend develops.
