### ISSUE TITLE
Examples of "Location Hours" data/UI

### ISSUE THREAD

**Issue by aNullValue** [hackforla/ballotnav#74]
### Overview

There are numerous ways that locations are scheduled by their respective jurisdictions. We need to come up with a good way to handle this in the UI. Perhaps we need a calendar view for the location?

### Resources/Instructions

These are different formats that I've seen:

* 24/7 (continuously) starting at a date/time, ending at a date/time

* Between a range of dates, the same open/close times every day, with no exceptions (i.e., "Every day, Oct 27 to Nov 3, 8-7")

* Open/close times vary consistent by range of days (i.e., "Mon-Fri 8-4; Sat 8-12")

* Open/close times vary by date without consistency beyond 1 week

An example of that last one is all of Ohio:
October 6-9: 8:00 a.m. - 5:00 p.m.
October 12-16: 8:00 a.m. - 5:00 p.m.
October 19-23: 8:00 a.m. - 6:00 p.m.
October 24: 8:00 a.m. - 4:00 p.m.
October 25: 1:00 p.m. - 5:00 p.m.
October 26-30: 8:00 a.m. - 7:00 p.m.
October 31: 8:00 a.m. - 4:00 p.m.
November 1: 1:00 p.m. - 5:00 p.m.
November 2: 8:00 a.m. - 2:00 p.m.
November 3: 6:30 a.m. - 7:30 p.m.

In all cases, the currently open/closed indicator is possible and IMO we should keep it.

As an idea, perhaps we could keep the current wireframe design that could accommodate the 24/7 locations (because that's super short to explain: "24/7, opens October 5", "24/7, until November 3 at 7:30 PM").

But for all of the others, perhaps we could do something along the lines of one of these descriptions ("Opens Monday at 8:00 AM", "Closes at 5:00 PM"), along with a link that opens a calendar view of the schedule for that location?

I know data, but I'm not great at UI; please go easy on me if this is illogical. I'll be happy to clarify or provide additional information if needed.

**Comment by kcoronel** [comment]
@fedelandini @IrinaRost an example above about how to design for a variety of office hours
