### ISSUE TITLE
Build Search interface

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/ballotnav#75]
### Overview
We need to have users be able to search by criteria and get back results based on location so that we accurately deliver them their EAJ info

### Action Items
Search (using interface code from FoodOasis for the search)
- [ ] Font End Dev (React)
   - [ ] Build out homepage according to design spec
- [ ] Back End
   - [ ] Identify criteria for ways they can search
  - [ ] api to send user input to and get back EAJ info to route to front end next page
- [ ] Front End integrator
   - [ ] integrate api into search

### Resources/Instructions
[foodoasis.la search example](http://foodoasis.la)
[Figma](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=344%3A3232)

[Issue 42](https://github.com/hackforla/ballotnav/issues/42)

**Comment by kcoronel** [comment]
Something to think about is adding something regarding current location backend / front end development? @Arjayellis  @ExperimentsInHonesty
