### ISSUE TITLE
Change Notification: State and EAJ Only (Design)

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#78]
### Overview
Users should have the capability to signup for notifications from BallotNav, notifying users about an update on their state's Secretary of State page so that they are not relying on old information or having to continually check our site.

### Dependency 
Feature: search by address #42  
Privacy Policy #104 

### User Acceptance Criteria
TBD based on compliance requirements

### Action Items
- [x] Product 
    - [x] Product will determine the exact language to achieve compliance 
       - [x] text for notifications sign up page 
       - [x] text for SMS messages, including confirmations and stop messages  
- [ ] Design 
   - [ ] Mock up interface design according to UX specs above

### Resources/Instructions
[Figma](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=344%3A3232)
[The Complete Guide to SMS Compliance](https://simpletexting.com/in-depth-guide/sms-compliance-guide/introduction-sms-compliance/)

**Comment by myastark** [comment]
![Uploading 78.png…]()

**Comment by myastark** [comment]
@kcoronel @Arjayellis can the UI display the specific type of EAJ it is in this text? i.e. in some cases it reads [dummy text] "Sign up for notifications for your county" and others it would read as "sign up for notifications for your parish" etc.? Under the assumption it can, i'm putting [EAJ] in as a placeholder but tell me if i'm wrong

**Comment by myastark** [comment]
@kcoronel @Arjayellis @ExperimentsInHonesty I know you told me to put it in the issue itself but I didn't want to mess it up. Also, what is the correct way to convey something in the SMS should be a link? I used "<text>" for now.

*UI text*
Last-minute changes to details about how to vote should be expected. Sign up for notifications for your State and/or [Eaj]

*SMS text
Successful signup*
Thank you for signing up for <BallotNav> notifications about changes to your State and/or [Eaj]’s voting rules. Text STOP to unsubscribe.

*Notification - State*
Hello! <BallotNav> has detected a change to your State’s voting rules. <Click to view your Secretary of State’s website.> Text STOP to unsubscribe.

*Notification - EAJ*
Hello! <BallotNav> has detected a change to your [Eaj]’s voting rules. <Click to view your [Eaj]’s website.> Text STOP to unsubscribe.

*Stop confirmation*
Thank you. You will no longer receive <BallotNav> notifications. Text START to resubscribe.

**Comment by kcoronel** [comment]
@IrinaRost @fedelandini can you confirm that these mock ups are in the Figma

**Comment by IrinaRost** [comment]
@kcoronel Checked, we have it
