### ISSUE TITLE
DNS setup for BallotNav.org

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#8]
### Overview
We need to be able to direct people to BallotNav.org so that they can find the information they need easily.

### Action Items

- [x] Mya to point the domain temporarily at the readme.
- [x] After website is ready for public, The DNS for AWS will be provided and the domain can point to that.

### Resources/Instructions
https://github.com/hackforla/ballotnav/blob/master/README.md

**Comment by kcoronel** [comment]
(http://ballotnav.org/) is registered

**Comment by ExperimentsInHonesty** [comment]
domain is resolving to readme and we will point dns when we have a website.
