### ISSUE TITLE
Share Buttons and function

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#86]
### Overview
We need to put a share npm on every page and on individual results, so by clicking on it determines what is shared. 

### Dependency
URL Paramaters #85 
**ADD FIGMA LINK AND PAGE NAME BEFORE ASSIGNING**

### User Acceptance Criteria (UAC)
When I share from the following location it provides a link and text connected to my social platform that allows me to post a link to:
- from homepage to same
- from overall search results with my state and county to same
- from an individual result

Also another person viewing my share will see what I see but not my personal information like my address or the results sorted by proximity to my address.  So If I search my address, and it brings up California, LA County and results in my surrounding areas, it would share California and LA County, but not my address.

### Action Items
- [ ] UI 
   - [ ] Adding share icons and wording to the following page
      - [ ] Homepage
      - [ ] State detail page #122 
      - [ ] Individual Search Results aka Location Summary / Location Details page
- [ ] Back End
  - [ ] Evaluate if the Reach Share NPM package will meet UAT
   - [ ] Provide code for front end to use on pages
- [ ] Font End Dev (React)
   - [ ] Build out according to design spec (see figma)

### Resources/Instructions
Possible tool to use [React Share npm package](https://www.npmjs.com/package/react-share)

**Comment by kcoronel** [comment]
@fedelandini @IrinaRost can you please confirm we have mocked up designs for this, thank you!
