### ISSUE TITLE
Change Notification: Location Specific plus State (Front End)

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#87]
### Overview
Users should have the ability to sign up for location specific page change notifications (will also include the SOC site update)

### Dependency 
Change Notification: State #78 
Feature: Search By Address #42  
Privacy Policy #104 

### User Acceptance Criteria
TBD based on compliance requirements

Error Handling requirements
- [ ] If null value or error is returned by API user is given a message stating that number is invalid and they are brought back to the "enter your number" function

### Action Items
- [x] Product 
    - [x] Product will determine the exact language to achieve compliance 
       - [ ] text for notifications sign up page 
       - [ ] text for SMS messages, including confirmations and stop messages  
- [x] UI 
   - [x] Mock up interface design according to spec
- [ ] Front End Dev (React)
   - [ ] Build out notification according to design spec
   - [ ] Link to privacy policy

### Resources/Instructions
[Figma](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=344%3A3232)
[The Complete Guide to SMS Compliance](https://simpletexting.com/in-depth-guide/sms-compliance-guide/introduction-sms-compliance/)
[EAJ Display](https://github.com/hackforla/ballotnav/issues/76)

**Comment by myastark** [comment]
<img width="157" alt="87" src="https://user-images.githubusercontent.com/54009156/93798278-45354d80-fbf2-11ea-8e31-b8173ff21ee7.png">

**Comment by myastark** [comment]
_UI text_
Sign up for notifications about last-minute changes to this location and to voting rules for your State

_SMS text
Successful signup_
Thank you for signing up for **BallotNav** notifications about changes to your local ballot drop-off locations or State voting rules. Text STOP to unsubscribe.

_Notification_ 
**BallotNav** has detected a change to your local ballot drop-off locations or State voting rules. **Click to view** Text STOP to unsubscribe.

_Stop confirmation_
Thank you. You will no longer receive **BallotNav** notifications. Text START to resubscribe.
