### ISSUE TITLE
Markdown inline: Display State Regulation Info

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#89]
### Overview
We need to allow users to view state regulation information from a displayed markdown in state sections. 

### Action Items
- [ ] Font End Dev (React)
   - [ ] Build out markdown according to design spec
- [ ] Back End
   - [ ] Identify criteria for ways they can display properly
  - [ ] api to send user input to and get back EAJ info to route to front end next page

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by kcoronel** [comment]
We have decided not to do this. See location header #117 ticket for details
